export interface QuizQuestion {
  id: number;
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
  question: string;
  options: string[];
  correctAnswer: number;
  hint: string;
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ANIMES - 50 perguntas
  { id: 1, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do protagonista de Naruto?', options: ['Naruto Uzumaki', 'Sasuke Uchiha', 'Kakashi Hatake', 'Sakura Haruno'], correctAnswer: 0, hint: 'É um ninja com cabelo louro' },
  { id: 2, category: 'Animes', difficulty: 'easy', question: 'Em qual cidade Ash começa sua jornada em Pokémon?', options: ['Pallet Town', 'Viridian City', 'Pewter City', 'Cerulean City'], correctAnswer: 0, hint: 'É a cidade natal de Ash' },
  { id: 3, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do melhor amigo de Luffy em One Piece?', options: ['Zoro', 'Nami', 'Usopp', 'Sanji'], correctAnswer: 0, hint: 'Ele usa três espadas' },
  { id: 4, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome da protagonista de Sailor Moon?', options: ['Usagi Tsukino', 'Ami Mizuno', 'Rei Hino', 'Makoto Kino'], correctAnswer: 0, hint: 'Ela é a Sailor Moon' },
  { id: 5, category: 'Animes', difficulty: 'easy', question: 'Em Dragon Ball, qual é o nome do melhor amigo de Goku?', options: ['Krillin', 'Vegeta', 'Gohan', 'Trunks'], correctAnswer: 0, hint: 'Ele é careca' },
  { id: 6, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do protagonista de My Hero Academia?', options: ['Midoriya Izuku', 'Bakugo Katsuki', 'All Might', 'Todoroki'], correctAnswer: 0, hint: 'Ele quer ser herói' },
  { id: 7, category: 'Animes', difficulty: 'easy', question: 'Em Attack on Titan, qual é o nome do protagonista?', options: ['Eren Yeager', 'Mikasa Ackerman', 'Armin Arlert', 'Levi Ackerman'], correctAnswer: 0, hint: 'Ele quer destruir os Titãs' },
  { id: 8, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do protagonista de Death Note?', options: ['Light Yagami', 'L', 'Ryuk', 'Misa Amane'], correctAnswer: 0, hint: 'Ele encontra um caderno' },
  { id: 9, category: 'Animes', difficulty: 'easy', question: 'Em Demon Slayer, qual é o nome do protagonista?', options: ['Tanjiro Kamado', 'Nezuko Kamado', 'Zenitsu Agatsuma', 'Inosuke Hashibira'], correctAnswer: 0, hint: 'Ele quer salvar sua irmã' },
  { id: 10, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do protagonista de Bleach?', options: ['Ichigo Kurosaki', 'Rukia Kuchiki', 'Orihime Inoue', 'Uryu Ishida'], correctAnswer: 0, hint: 'Ele é um Shinigami' },
  { id: 11, category: 'Animes', difficulty: 'medium', question: 'Qual é o nome do Titã Colossal em Attack on Titan?', options: ['Bertholdt Hoover', 'Reiner Braun', 'Annie Leonhart', 'Eren Yeager'], correctAnswer: 0, hint: 'Ele é um dos Titãs' },
  { id: 12, category: 'Animes', difficulty: 'medium', question: 'Em My Hero Academia, qual é o nome do vilão principal?', options: ['All For One', 'Shigaraki Tomura', 'Dabi', 'Twice'], correctAnswer: 0, hint: 'Ele dá poderes' },
  { id: 13, category: 'Animes', difficulty: 'medium', question: 'Qual é o nome do Hokage original em Naruto?', options: ['Hashirama Senju', 'Tobirama Senju', 'Hiruzen Sarutobi', 'Minato Namikaze'], correctAnswer: 0, hint: 'Ele é o primeiro' },
  { id: 14, category: 'Animes', difficulty: 'medium', question: 'Em Jujutsu Kaisen, qual é o nome do rei das maldições?', options: ['Sukuna', 'Mahito', 'Jogo', 'Hanami'], correctAnswer: 0, hint: 'Ele está dentro de Yuji' },
  { id: 15, category: 'Animes', difficulty: 'medium', question: 'Qual é o criador de Naruto?', options: ['Masashi Kishimoto', 'Akira Toriyama', 'Eiichiro Oda', 'Tite Kubo'], correctAnswer: 0, hint: 'Ele é o mangaka' },
  { id: 16, category: 'Animes', difficulty: 'hard', question: 'Qual é o nome completo do protagonista de Naruto?', options: ['Naruto Uzumaki', 'Naruto Namikaze', 'Naruto Senju', 'Naruto Uchiha'], correctAnswer: 0, hint: 'É seu nome verdadeiro' },
  { id: 17, category: 'Animes', difficulty: 'hard', question: 'Em Attack on Titan, qual é o nome real de Eren?', options: ['Eren Yeager', 'Eren Kruger', 'Eren Jaeger', 'Eren Titan'], correctAnswer: 0, hint: 'É seu nome de nascimento' },
  { id: 18, category: 'Animes', difficulty: 'hard', question: 'Qual é o criador de One Piece?', options: ['Eiichiro Oda', 'Akira Toriyama', 'Masashi Kishimoto', 'Tite Kubo'], correctAnswer: 0, hint: 'Ele é o mangaka' },
  { id: 19, category: 'Animes', difficulty: 'hard', question: 'Qual é o criador de Bleach?', options: ['Tite Kubo', 'Akira Toriyama', 'Eiichiro Oda', 'Masashi Kishimoto'], correctAnswer: 0, hint: 'Ele é o mangaka' },
  { id: 20, category: 'Animes', difficulty: 'hard', question: 'Qual é o criador de Dragon Ball?', options: ['Akira Toriyama', 'Eiichiro Oda', 'Masashi Kishimoto', 'Tite Kubo'], correctAnswer: 0, hint: 'Ele é o mangaka' },
  { id: 21, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista é um caçador de recompensas?', options: ['Cowboy Bebop', 'Trigun', 'Outlaw Star', 'Samurai Champloo'], correctAnswer: 0, hint: 'Tem uma nave' },
  { id: 22, category: 'Animes', difficulty: 'easy', question: 'Qual anime tem como tema principal duelos de cartas?', options: ['Yu-Gi-Oh', 'Beyblade', 'Digimon', 'Pokémon'], correctAnswer: 0, hint: 'Monstros de duelo' },
  { id: 23, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista tem poderes psíquicos?', options: ['Mob Psycho 100', 'My Hero Academia', 'Jujutsu Kaisen', 'Demon Slayer'], correctAnswer: 0, hint: 'Seu apelido é Mob' },
  { id: 24, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome da organização em Naruto?', options: ['Akatsuki', 'Taka', 'Hebi', 'Otogakure'], correctAnswer: 0, hint: 'É uma organização de vilões' },
  { id: 25, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista é um alquimista?', options: ['Fullmetal Alchemist', 'Steins;Gate', 'Code Geass', 'Death Note'], correctAnswer: 0, hint: 'Tem um irmão' },
  { id: 26, category: 'Animes', difficulty: 'medium', question: 'Qual é o nome do poder em Death Note?', options: ['Shinigami Eyes', 'Geass', 'Code', 'Deathnote'], correctAnswer: 0, hint: 'Mata pessoas' },
  { id: 27, category: 'Animes', difficulty: 'medium', question: 'Em qual anime o protagonista pilota um robô gigante?', options: ['Neon Genesis Evangelion', 'Gurren Lagann', 'Code Geass', 'Kill la Kill'], correctAnswer: 0, hint: 'Tem um Eva' },
  { id: 28, category: 'Animes', difficulty: 'medium', question: 'Qual é o nome do torneio em Dragon Ball?', options: ['Tenkaichi Budokai', 'World Tournament', 'Martial Arts Tournament', 'Tournament of Power'], correctAnswer: 0, hint: 'É um torneio de artes marciais' },
  { id: 29, category: 'Animes', difficulty: 'medium', question: 'Em qual anime o protagonista é um vampiro?', options: ['Hellsing', 'Tokyo Ghoul', 'Parasyte', 'Black Butler'], correctAnswer: 0, hint: 'Ele é um vampiro imortal' },
  { id: 30, category: 'Animes', difficulty: 'hard', question: 'Em qual anime o protagonista viaja entre dimensões?', options: ['Tsubasa Reservoir Chronicle', 'xxxHolic', 'Cardcaptor Sakura', 'Chobits'], correctAnswer: 0, hint: 'Ele viaja entre mundos' },
  { id: 31, category: 'Animes', difficulty: 'easy', question: 'Qual anime tem como tema principal pokémons?', options: ['Pokémon', 'Digimon', 'Beyblade', 'Yu-Gi-Oh'], correctAnswer: 0, hint: 'Gotta catch em all' },
  { id: 32, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista é um pirata?', options: ['One Piece', 'Bleach', 'Naruto', 'My Hero Academia'], correctAnswer: 0, hint: 'Ele quer ser Rei dos Piratas' },
  { id: 33, category: 'Animes', difficulty: 'easy', question: 'Qual anime tem como tema principal ninjas?', options: ['Naruto', 'Bleach', 'One Piece', 'My Hero Academia'], correctAnswer: 0, hint: 'Tem clãs de ninjas' },
  { id: 34, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista é um herói?', options: ['My Hero Academia', 'Naruto', 'Bleach', 'One Piece'], correctAnswer: 0, hint: 'Ele quer ser herói' },
  { id: 35, category: 'Animes', difficulty: 'easy', question: 'Qual anime tem como tema principal titãs?', options: ['Attack on Titan', 'Bleach', 'Naruto', 'One Piece'], correctAnswer: 0, hint: 'Tem muros gigantes' },
  { id: 36, category: 'Animes', difficulty: 'medium', question: 'Em qual anime o protagonista é um shinigami?', options: ['Bleach', 'Death Note', 'Tokyo Ghoul', 'Parasyte'], correctAnswer: 0, hint: 'Ele protege almas' },
  { id: 37, category: 'Animes', difficulty: 'medium', question: 'Qual anime tem como tema principal demônios?', options: ['Demon Slayer', 'Bleach', 'Naruto', 'One Piece'], correctAnswer: 0, hint: 'Tem demônios para matar' },
  { id: 38, category: 'Animes', difficulty: 'medium', question: 'Em qual anime o protagonista é um mago?', options: ['Fate/Stay Night', 'My Hero Academia', 'Jujutsu Kaisen', 'Demon Slayer'], correctAnswer: 0, hint: 'Ele participa de uma guerra' },
  { id: 39, category: 'Animes', difficulty: 'hard', question: 'Qual anime tem como tema principal magia?', options: ['Fate/Stay Night', 'My Hero Academia', 'Jujutsu Kaisen', 'Demon Slayer'], correctAnswer: 0, hint: 'Tem um Graal Sagrado' },
  { id: 40, category: 'Animes', difficulty: 'hard', question: 'Em qual anime o protagonista é um estudante de magia?', options: ['Fate/Stay Night', 'My Hero Academia', 'Jujutsu Kaisen', 'Demon Slayer'], correctAnswer: 0, hint: 'Ele vai para uma escola' },
  { id: 41, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do melhor amigo de Naruto?', options: ['Sasuke Uchiha', 'Kakashi Hatake', 'Sakura Haruno', 'Shikamaru Nara'], correctAnswer: 0, hint: 'Ele é um Uchiha' },
  { id: 42, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista tem cabelo rosa?', options: ['Demon Slayer', 'My Hero Academia', 'Jujutsu Kaisen', 'Attack on Titan'], correctAnswer: 0, hint: 'Ele é um caçador de demônios' },
  { id: 43, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome do professor de Naruto?', options: ['Kakashi Hatake', 'Jiraiya', 'Orochimaru', 'Tsunade'], correctAnswer: 0, hint: 'Ele tem um olho especial' },
  { id: 44, category: 'Animes', difficulty: 'easy', question: 'Em qual anime o protagonista é um estudante de herói?', options: ['My Hero Academia', 'Naruto', 'Bleach', 'One Piece'], correctAnswer: 0, hint: 'Ele vai para U.A.' },
  { id: 45, category: 'Animes', difficulty: 'easy', question: 'Qual é o nome da melhor amiga de Naruto?', options: ['Sakura Haruno', 'Ino Yamanaka', 'Hinata Hyuga', 'Tenten'], correctAnswer: 0, hint: 'Ela tem cabelo rosa' },
  { id: 46, category: 'Animes', difficulty: 'medium', question: 'Qual é o nome do vilão em Naruto Shippuden?', options: ['Madara Uchiha', 'Obito Uchiha', 'Itachi Uchiha', 'Sasuke Uchiha'], correctAnswer: 0, hint: 'Ele é um Uchiha' },
  { id: 47, category: 'Animes', difficulty: 'medium', question: 'Em qual anime o protagonista come pessoas?', options: ['Tokyo Ghoul', 'Parasyte', 'Bleach', 'Death Note'], correctAnswer: 0, hint: 'Ele é um ghoul' },
  { id: 48, category: 'Animes', difficulty: 'medium', question: 'Qual é o nome do melhor amigo de Ichigo em Bleach?', options: ['Rukia Kuchiki', 'Orihime Inoue', 'Uryu Ishida', 'Chad Yasutora'], correctAnswer: 0, hint: 'Ela é uma Shinigami' },
  { id: 49, category: 'Animes', difficulty: 'hard', question: 'Em qual anime o protagonista é um estudante de jujutsu?', options: ['Jujutsu Kaisen', 'My Hero Academia', 'Demon Slayer', 'Attack on Titan'], correctAnswer: 0, hint: 'Ele engole um dedo' },
  { id: 50, category: 'Animes', difficulty: 'hard', question: 'Qual é o nome do poder em Jujutsu Kaisen?', options: ['Jujutsu', 'Cursed Energy', 'Maldição', 'Poder'], correctAnswer: 0, hint: 'É uma energia mágica' },

  // MATEMÁTICA - 50 perguntas
  { id: 51, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 2 + 3?', options: ['5', '6', '4', '7'], correctAnswer: 0, hint: 'Conte nos dedos' },
  { id: 52, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 10 - 5?', options: ['5', '15', '3', '8'], correctAnswer: 0, hint: 'É a metade de 10' },
  { id: 53, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 3 × 4?', options: ['12', '7', '10', '15'], correctAnswer: 0, hint: '3 vezes 4' },
  { id: 54, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 20 ÷ 4?', options: ['5', '10', '3', '8'], correctAnswer: 0, hint: 'Divida 20 em 4 partes' },
  { id: 55, category: 'Matemática', difficulty: 'easy', question: 'Qual número vem após 99?', options: ['100', '98', '101', '99'], correctAnswer: 0, hint: 'É o primeiro número de 3 dígitos' },
  { id: 56, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 7 + 8?', options: ['15', '14', '16', '13'], correctAnswer: 0, hint: 'Conte bem' },
  { id: 57, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 12 - 3?', options: ['9', '8', '10', '11'], correctAnswer: 0, hint: 'Subtraia 3 de 12' },
  { id: 58, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 5 × 5?', options: ['25', '20', '30', '15'], correctAnswer: 0, hint: '5 vezes 5' },
  { id: 59, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 18 ÷ 2?', options: ['9', '8', '10', '7'], correctAnswer: 0, hint: 'Divida 18 por 2' },
  { id: 60, category: 'Matemática', difficulty: 'easy', question: 'Qual é o dobro de 6?', options: ['12', '10', '14', '8'], correctAnswer: 0, hint: '6 × 2' },
  { id: 61, category: 'Matemática', difficulty: 'medium', question: 'Quanto é 15 × 12?', options: ['180', '200', '150', '170'], correctAnswer: 0, hint: 'Multiplique 15 por 12' },
  { id: 62, category: 'Matemática', difficulty: 'medium', question: 'Quanto é 144 ÷ 12?', options: ['12', '14', '10', '15'], correctAnswer: 0, hint: 'Divida 144 por 12' },
  { id: 63, category: 'Matemática', difficulty: 'medium', question: 'Qual é a raiz quadrada de 64?', options: ['8', '7', '9', '6'], correctAnswer: 0, hint: '8 × 8 = 64' },
  { id: 64, category: 'Matemática', difficulty: 'medium', question: 'Quanto é 25% de 100?', options: ['25', '50', '75', '10'], correctAnswer: 0, hint: 'É um quarto' },
  { id: 65, category: 'Matemática', difficulty: 'medium', question: 'Qual é o resultado de 2³?', options: ['8', '6', '9', '4'], correctAnswer: 0, hint: '2 × 2 × 2' },
  { id: 66, category: 'Matemática', difficulty: 'hard', question: 'Qual é a raiz quadrada de 144?', options: ['12', '11', '13', '10'], correctAnswer: 0, hint: '12 × 12 = 144' },
  { id: 67, category: 'Matemática', difficulty: 'hard', question: 'Quanto é 7² + 3²?', options: ['58', '60', '50', '52'], correctAnswer: 0, hint: '49 + 9' },
  { id: 68, category: 'Matemática', difficulty: 'hard', question: 'Qual é 50% de 200?', options: ['100', '150', '50', '75'], correctAnswer: 0, hint: 'É a metade' },
  { id: 69, category: 'Matemática', difficulty: 'hard', question: 'Quanto é 3⁴?', options: ['81', '64', '100', '49'], correctAnswer: 0, hint: '3 × 3 × 3 × 3' },
  { id: 70, category: 'Matemática', difficulty: 'hard', question: 'Qual é o resultado de √256?', options: ['16', '15', '17', '14'], correctAnswer: 0, hint: '16 × 16 = 256' },
  { id: 71, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 4 + 6?', options: ['10', '9', '11', '8'], correctAnswer: 0, hint: 'Conte bem' },
  { id: 72, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 15 - 7?', options: ['8', '9', '6', '7'], correctAnswer: 0, hint: 'Subtraia 7 de 15' },
  { id: 73, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 6 × 7?', options: ['42', '40', '45', '38'], correctAnswer: 0, hint: '6 vezes 7' },
  { id: 74, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 30 ÷ 5?', options: ['6', '5', '7', '4'], correctAnswer: 0, hint: 'Divida 30 por 5' },
  { id: 75, category: 'Matemática', difficulty: 'easy', question: 'Qual é o triplo de 5?', options: ['15', '10', '20', '12'], correctAnswer: 0, hint: '5 × 3' },
  { id: 76, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 8 + 9?', options: ['17', '16', '18', '15'], correctAnswer: 0, hint: 'Conte bem' },
  { id: 77, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 20 - 8?', options: ['12', '13', '11', '10'], correctAnswer: 0, hint: 'Subtraia 8 de 20' },
  { id: 78, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 8 × 8?', options: ['64', '60', '68', '56'], correctAnswer: 0, hint: '8 vezes 8' },
  { id: 79, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 36 ÷ 6?', options: ['6', '5', '7', '4'], correctAnswer: 0, hint: 'Divida 36 por 6' },
  { id: 80, category: 'Matemática', difficulty: 'easy', question: 'Qual é o quádruplo de 4?', options: ['16', '12', '20', '14'], correctAnswer: 0, hint: '4 × 4' },
  { id: 81, category: 'Matemática', difficulty: 'medium', question: 'Quanto é 25 × 8?', options: ['200', '180', '220', '190'], correctAnswer: 0, hint: 'Multiplique 25 por 8' },
  { id: 82, category: 'Matemática', difficulty: 'medium', question: 'Quanto é 100 ÷ 5?', options: ['20', '25', '15', '18'], correctAnswer: 0, hint: 'Divida 100 por 5' },
  { id: 83, category: 'Matemática', difficulty: 'medium', question: 'Qual é a raiz quadrada de 100?', options: ['10', '9', '11', '8'], correctAnswer: 0, hint: '10 × 10 = 100' },
  { id: 84, category: 'Matemática', difficulty: 'medium', question: 'Quanto é 30% de 100?', options: ['30', '20', '40', '25'], correctAnswer: 0, hint: 'É 30 por cento' },
  { id: 85, category: 'Matemática', difficulty: 'medium', question: 'Qual é o resultado de 3³?', options: ['27', '25', '30', '20'], correctAnswer: 0, hint: '3 × 3 × 3' },
  { id: 86, category: 'Matemática', difficulty: 'hard', question: 'Qual é a raiz quadrada de 169?', options: ['13', '12', '14', '11'], correctAnswer: 0, hint: '13 × 13 = 169' },
  { id: 87, category: 'Matemática', difficulty: 'hard', question: 'Quanto é 5² + 4²?', options: ['41', '40', '42', '39'], correctAnswer: 0, hint: '25 + 16' },
  { id: 88, category: 'Matemática', difficulty: 'hard', question: 'Qual é 75% de 100?', options: ['75', '70', '80', '65'], correctAnswer: 0, hint: 'É três quartos' },
  { id: 89, category: 'Matemática', difficulty: 'hard', question: 'Quanto é 2⁵?', options: ['32', '30', '35', '28'], correctAnswer: 0, hint: '2 × 2 × 2 × 2 × 2' },
  { id: 90, category: 'Matemática', difficulty: 'hard', question: 'Qual é o resultado de √225?', options: ['15', '14', '16', '13'], correctAnswer: 0, hint: '15 × 15 = 225' },
  { id: 91, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 1 + 1?', options: ['2', '3', '1', '4'], correctAnswer: 0, hint: 'Simples' },
  { id: 92, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 5 - 2?', options: ['3', '4', '2', '5'], correctAnswer: 0, hint: 'Subtraia 2 de 5' },
  { id: 93, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 2 × 2?', options: ['4', '3', '5', '2'], correctAnswer: 0, hint: '2 vezes 2' },
  { id: 94, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 10 ÷ 2?', options: ['5', '4', '6', '3'], correctAnswer: 0, hint: 'Divida 10 por 2' },
  { id: 95, category: 'Matemática', difficulty: 'easy', question: 'Qual é o dobro de 3?', options: ['6', '5', '7', '4'], correctAnswer: 0, hint: '3 × 2' },
  { id: 96, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 9 + 1?', options: ['10', '9', '11', '8'], correctAnswer: 0, hint: 'Conte bem' },
  { id: 97, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 16 - 6?', options: ['10', '11', '9', '12'], correctAnswer: 0, hint: 'Subtraia 6 de 16' },
  { id: 98, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 9 × 9?', options: ['81', '80', '82', '79'], correctAnswer: 0, hint: '9 vezes 9' },
  { id: 99, category: 'Matemática', difficulty: 'easy', question: 'Quanto é 45 ÷ 5?', options: ['9', '8', '10', '7'], correctAnswer: 0, hint: 'Divida 45 por 5' },
  { id: 100, category: 'Matemática', difficulty: 'easy', question: 'Qual é o quíntuplo de 2?', options: ['10', '8', '12', '6'], correctAnswer: 0, hint: '2 × 5' },

  // CIÊNCIAS - 50 perguntas
  { id: 101, category: 'Ciências', difficulty: 'easy', question: 'Quantos planetas existem no Sistema Solar?', options: ['8', '9', '7', '10'], correctAnswer: 0, hint: 'Plutão não é mais' },
  { id: 102, category: 'Ciências', difficulty: 'easy', question: 'Qual é o planeta mais próximo do Sol?', options: ['Mercúrio', 'Vênus', 'Terra', 'Marte'], correctAnswer: 0, hint: 'É o menor' },
  { id: 103, category: 'Ciências', difficulty: 'easy', question: 'Qual animal é o mais rápido do mundo?', options: ['Guepardo', 'Leão', 'Gazela', 'Zebra'], correctAnswer: 0, hint: 'Tem manchas' },
  { id: 104, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior animal do mundo?', options: ['Baleia Azul', 'Elefante', 'Girafa', 'Rinoceronte'], correctAnswer: 0, hint: 'Vive no oceano' },
  { id: 105, category: 'Ciências', difficulty: 'easy', question: 'Quantos ossos tem um adulto humano?', options: ['206', '186', '226', '196'], correctAnswer: 0, hint: 'É mais de 200' },
  { id: 106, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior órgão do corpo humano?', options: ['Pele', 'Coração', 'Cérebro', 'Fígado'], correctAnswer: 0, hint: 'Cobre todo o corpo' },
  { id: 107, category: 'Ciências', difficulty: 'easy', question: 'Quantos dentes tem um adulto humano?', options: ['32', '30', '28', '36'], correctAnswer: 0, hint: 'É mais de 30' },
  { id: 108, category: 'Ciências', difficulty: 'easy', question: 'Qual é a temperatura normal do corpo humano?', options: ['37°C', '36°C', '38°C', '35°C'], correctAnswer: 0, hint: 'É perto de 37' },
  { id: 109, category: 'Ciências', difficulty: 'easy', question: 'Qual elemento tem o símbolo O?', options: ['Oxigênio', 'Ouro', 'Osmio', 'Ósmio'], correctAnswer: 0, hint: 'Respiramos' },
  { id: 110, category: 'Ciências', difficulty: 'easy', question: 'Qual é o gás mais abundante na atmosfera?', options: ['Nitrogênio', 'Oxigênio', 'Argônio', 'Dióxido de carbono'], correctAnswer: 0, hint: 'É mais de 70%' },
  { id: 111, category: 'Ciências', difficulty: 'medium', question: 'Qual é a velocidade da luz?', options: ['300.000 km/s', '150.000 km/s', '450.000 km/s', '200.000 km/s'], correctAnswer: 0, hint: 'É muito rápido' },
  { id: 112, category: 'Ciências', difficulty: 'medium', question: 'Qual é o planeta mais quente do Sistema Solar?', options: ['Vênus', 'Mercúrio', 'Marte', 'Júpiter'], correctAnswer: 0, hint: 'Tem uma atmosfera' },
  { id: 113, category: 'Ciências', difficulty: 'medium', question: 'Quantas fases tem a Lua?', options: ['4', '3', '5', '6'], correctAnswer: 0, hint: 'São as principais' },
  { id: 114, category: 'Ciências', difficulty: 'medium', question: 'Qual é o maior osso do corpo humano?', options: ['Fêmur', 'Tíbia', 'Úmero', 'Rádio'], correctAnswer: 0, hint: 'Fica na perna' },
  { id: 115, category: 'Ciências', difficulty: 'medium', question: 'Quantas câmaras tem o coração humano?', options: ['4', '3', '5', '2'], correctAnswer: 0, hint: 'São 2 átrios e 2' },
  { id: 116, category: 'Ciências', difficulty: 'hard', question: 'Qual é a distância da Terra ao Sol?', options: ['150 milhões de km', '100 milhões de km', '200 milhões de km', '250 milhões de km'], correctAnswer: 0, hint: 'É chamada de UA' },
  { id: 117, category: 'Ciências', difficulty: 'hard', question: 'Qual é o elemento mais pesado natural?', options: ['Urânio', 'Plutônio', 'Tório', 'Protactínio'], correctAnswer: 0, hint: 'Tem número atômico 92' },
  { id: 118, category: 'Ciências', difficulty: 'hard', question: 'Quantos cromossomos tem um ser humano?', options: ['46', '44', '48', '50'], correctAnswer: 0, hint: 'São 23 pares' },
  { id: 119, category: 'Ciências', difficulty: 'hard', question: 'Qual é a velocidade do som?', options: ['340 m/s', '300 m/s', '400 m/s', '250 m/s'], correctAnswer: 0, hint: 'No ar, a 20°C' },
  { id: 120, category: 'Ciências', difficulty: 'hard', question: 'Qual é o elemento mais abundante do universo?', options: ['Hidrogênio', 'Hélio', 'Oxigênio', 'Carbono'], correctAnswer: 0, hint: 'É o primeiro' },
  { id: 121, category: 'Ciências', difficulty: 'easy', question: 'Qual é a maior floresta do mundo?', options: ['Floresta Amazônica', 'Floresta do Congo', 'Floresta de Taiga', 'Floresta Tropical'], correctAnswer: 0, hint: 'Fica na América do Sul' },
  { id: 122, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior oceano do mundo?', options: ['Oceano Pacífico', 'Oceano Atlântico', 'Oceano Índico', 'Oceano Ártico'], correctAnswer: 0, hint: 'É o maior' },
  { id: 123, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior deserto do mundo?', options: ['Deserto do Saara', 'Deserto de Gobi', 'Deserto de Kalahari', 'Deserto da Arábia'], correctAnswer: 0, hint: 'Fica na África' },
  { id: 124, category: 'Ciências', difficulty: 'easy', question: 'Qual é a montanha mais alta do mundo?', options: ['Monte Everest', 'K2', 'Kangchenjunga', 'Lhotse'], correctAnswer: 0, hint: 'Fica no Himalaia' },
  { id: 125, category: 'Ciências', difficulty: 'easy', question: 'Qual é o rio mais comprido do mundo?', options: ['Rio Nilo', 'Rio Amazonas', 'Rio Yangtze', 'Rio Mississípi'], correctAnswer: 0, hint: 'Fica na África' },
  { id: 126, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior lago do mundo?', options: ['Mar Cáspio', 'Lago Baikal', 'Lago Superior', 'Lago Vitória'], correctAnswer: 0, hint: 'Fica entre Ásia e Europa' },
  { id: 127, category: 'Ciências', difficulty: 'easy', question: 'Quantos continentes existem?', options: ['7', '6', '5', '8'], correctAnswer: 0, hint: 'São sete' },
  { id: 128, category: 'Ciências', difficulty: 'easy', question: 'Qual é o continente mais frio?', options: ['Antártida', 'Ártico', 'Groenlândia', 'Sibéria'], correctAnswer: 0, hint: 'Tem muito gelo' },
  { id: 129, category: 'Ciências', difficulty: 'easy', question: 'Qual é o continente mais quente?', options: ['África', 'América do Sul', 'Ásia', 'Austrália'], correctAnswer: 0, hint: 'Tem muitos desertos' },
  { id: 130, category: 'Ciências', difficulty: 'easy', question: 'Qual é o continente mais populoso?', options: ['Ásia', 'África', 'Europa', 'América do Norte'], correctAnswer: 0, hint: 'Tem mais de 4 bilhões' },
  { id: 131, category: 'Ciências', difficulty: 'medium', question: 'Qual é a profundidade máxima do Oceano Pacífico?', options: ['11.000 metros', '10.000 metros', '12.000 metros', '9.000 metros'], correctAnswer: 0, hint: 'É muito profundo' },
  { id: 132, category: 'Ciências', difficulty: 'medium', question: 'Qual é a altura máxima da atmosfera?', options: ['100 km', '80 km', '120 km', '60 km'], correctAnswer: 0, hint: 'É chamada de Kármán' },
  { id: 133, category: 'Ciências', difficulty: 'medium', question: 'Qual é o tempo de órbita da Terra ao redor do Sol?', options: ['365 dias', '360 dias', '370 dias', '355 dias'], correctAnswer: 0, hint: 'É um ano' },
  { id: 134, category: 'Ciências', difficulty: 'medium', question: 'Qual é o tempo de órbita da Lua ao redor da Terra?', options: ['27 dias', '25 dias', '30 dias', '20 dias'], correctAnswer: 0, hint: 'É aproximadamente' },
  { id: 135, category: 'Ciências', difficulty: 'medium', question: 'Qual é a idade da Terra?', options: ['4,5 bilhões de anos', '3 bilhões de anos', '5 bilhões de anos', '2 bilhões de anos'], correctAnswer: 0, hint: 'É muito antiga' },
  { id: 136, category: 'Ciências', difficulty: 'hard', question: 'Qual é a massa do Sol?', options: ['2 × 10³⁰ kg', '1 × 10³⁰ kg', '3 × 10³⁰ kg', '1,5 × 10³⁰ kg'], correctAnswer: 0, hint: 'É muito pesado' },
  { id: 137, category: 'Ciências', difficulty: 'hard', question: 'Qual é a temperatura do núcleo do Sol?', options: ['15 milhões de K', '10 milhões de K', '20 milhões de K', '5 milhões de K'], correctAnswer: 0, hint: 'É muito quente' },
  { id: 138, category: 'Ciências', difficulty: 'hard', question: 'Qual é a velocidade de escape da Terra?', options: ['11,2 km/s', '10 km/s', '12 km/s', '9 km/s'], correctAnswer: 0, hint: 'É a velocidade mínima' },
  { id: 139, category: 'Ciências', difficulty: 'hard', question: 'Qual é a pressão atmosférica ao nível do mar?', options: ['101.325 Pa', '100.000 Pa', '102.000 Pa', '99.000 Pa'], correctAnswer: 0, hint: 'É 1 atm' },
  { id: 140, category: 'Ciências', difficulty: 'hard', question: 'Qual é o número de Avogadro?', options: ['6,022 × 10²³', '6 × 10²³', '6,5 × 10²³', '5,5 × 10²³'], correctAnswer: 0, hint: 'É uma constante' },
  { id: 141, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior animal terrestre?', options: ['Elefante', 'Girafa', 'Hipopótamo', 'Rinoceronte'], correctAnswer: 0, hint: 'É muito grande' },
  { id: 142, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior pássaro do mundo?', options: ['Avestruz', 'Ema', 'Cisne', 'Ganso'], correctAnswer: 0, hint: 'Não voa' },
  { id: 143, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior peixe do mundo?', options: ['Tubarão-baleia', 'Tubarão-branco', 'Peixe-lua', 'Esturjão'], correctAnswer: 0, hint: 'É um tubarão' },
  { id: 144, category: 'Ciências', difficulty: 'easy', question: 'Qual é o maior inseto do mundo?', options: ['Besouro Hércules', 'Libélula', 'Barata', 'Gafanhoto'], correctAnswer: 0, hint: 'É um besouro' },
  { id: 145, category: 'Ciências', difficulty: 'easy', question: 'Qual é o animal mais venenoso do mundo?', options: ['Sapo-azul', 'Cobra-coral', 'Aranha-de-teia-de-funil', 'Escorpião'], correctAnswer: 0, hint: 'É um sapo' },
  { id: 146, category: 'Ciências', difficulty: 'easy', question: 'Qual é o animal que vive mais tempo?', options: ['Tartaruga-gigante', 'Baleia', 'Papagaio', 'Elefante'], correctAnswer: 0, hint: 'É uma tartaruga' },
  { id: 147, category: 'Ciências', difficulty: 'easy', question: 'Qual é o animal mais inteligente do mundo?', options: ['Golfinho', 'Chimpanzé', 'Elefante', 'Corvo'], correctAnswer: 0, hint: 'Vive no oceano' },
  { id: 148, category: 'Ciências', difficulty: 'easy', question: 'Qual é o animal mais forte do mundo?', options: ['Besouro-escaravelho', 'Leão', 'Elefante', 'Rinoceronte'], correctAnswer: 0, hint: 'É um besouro' },
  { id: 149, category: 'Ciências', difficulty: 'easy', question: 'Qual é o animal mais raro do mundo?', options: ['Panda-gigante', 'Rinoceronte-de-Java', 'Lince-ibérico', 'Morcego-com-nariz-de-folha'], correctAnswer: 0, hint: 'Vive na China' },
  { id: 150, category: 'Ciências', difficulty: 'easy', question: 'Qual é o animal que mais dorme?', options: ['Coala', 'Preguiça', 'Gato', 'Urso'], correctAnswer: 0, hint: 'Dorme até 22 horas' },

  // GEOGRAFIA - 50 perguntas
  { id: 151, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital do Brasil?', options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], correctAnswer: 0, hint: 'É uma cidade planejada' },
  { id: 152, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital da França?', options: ['Paris', 'Lyon', 'Marselha', 'Toulouse'], correctAnswer: 0, hint: 'Tem a Torre Eiffel' },
  { id: 153, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital da Itália?', options: ['Roma', 'Milão', 'Veneza', 'Florença'], correctAnswer: 0, hint: 'Tem o Coliseu' },
  { id: 154, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital da Espanha?', options: ['Madri', 'Barcelona', 'Sevilha', 'Valência'], correctAnswer: 0, hint: 'É a maior cidade' },
  { id: 155, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital de Portugal?', options: ['Lisboa', 'Porto', 'Covilhã', 'Faro'], correctAnswer: 0, hint: 'Fica perto do Tejo' },
  { id: 156, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital do Japão?', options: ['Tóquio', 'Kyoto', 'Osaka', 'Yokohama'], correctAnswer: 0, hint: 'É a maior metrópole' },
  { id: 157, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital da China?', options: ['Pequim', 'Xangai', 'Guangzhou', 'Chongqing'], correctAnswer: 0, hint: 'Tem a Grande Muralha' },
  { id: 158, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital da Índia?', options: ['Nova Delhi', 'Mumbai', 'Bangalore', 'Calcutá'], correctAnswer: 0, hint: 'É a capital política' },
  { id: 159, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital do Egito?', options: ['Cairo', 'Alexandria', 'Giza', 'Luxor'], correctAnswer: 0, hint: 'Tem as pirâmides' },
  { id: 160, category: 'Geografia', difficulty: 'easy', question: 'Qual é a capital da Austrália?', options: ['Camberra', 'Sydney', 'Melbourne', 'Brisbane'], correctAnswer: 0, hint: 'Não é Sydney' },
  { id: 161, category: 'Geografia', difficulty: 'medium', question: 'Qual é a capital da Rússia?', options: ['Moscou', 'São Petersburgo', 'Novosibirsk', 'Yekaterinburg'], correctAnswer: 0, hint: 'É a maior cidade' },
  { id: 162, category: 'Geografia', difficulty: 'medium', question: 'Qual é a capital do Canadá?', options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'], correctAnswer: 0, hint: 'Não é Toronto' },
  { id: 163, category: 'Geografia', difficulty: 'medium', question: 'Qual é a capital dos EUA?', options: ['Washington', 'Nova York', 'Los Angeles', 'Chicago'], correctAnswer: 0, hint: 'Não é Nova York' },
  { id: 164, category: 'Geografia', difficulty: 'medium', question: 'Qual é a capital do México?', options: ['Cidade do México', 'Guadalajara', 'Monterrey', 'Cancún'], correctAnswer: 0, hint: 'É a maior metrópole' },
  { id: 165, category: 'Geografia', difficulty: 'medium', question: 'Qual é a capital da Argentina?', options: ['Buenos Aires', 'Córdoba', 'Rosário', 'Mendoza'], correctAnswer: 0, hint: 'É a maior cidade' },
  { id: 166, category: 'Geografia', difficulty: 'hard', question: 'Qual é a capital da Tailândia?', options: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'], correctAnswer: 0, hint: 'É a maior metrópole' },
  { id: 167, category: 'Geografia', difficulty: 'hard', question: 'Qual é a capital da Vietnã?', options: ['Hanói', 'Ho Chi Minh', 'Haiphong', 'Da Nang'], correctAnswer: 0, hint: 'É a capital política' },
  { id: 168, category: 'Geografia', difficulty: 'hard', question: 'Qual é a capital da Malásia?', options: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Johor Bahru'], correctAnswer: 0, hint: 'É a maior metrópole' },
  { id: 169, category: 'Geografia', difficulty: 'hard', question: 'Qual é a capital da Indonésia?', options: ['Jacarta', 'Surabaya', 'Bandung', 'Medan'], correctAnswer: 0, hint: 'É a maior metrópole' },
  { id: 170, category: 'Geografia', difficulty: 'hard', question: 'Qual é a capital das Filipinas?', options: ['Manila', 'Cebu', 'Davao', 'Quezon City'], correctAnswer: 0, hint: 'É a maior metrópole' },
  { id: 171, category: 'Geografia', difficulty: 'easy', question: 'Qual país tem a maior população?', options: ['Índia', 'China', 'EUA', 'Indonésia'], correctAnswer: 0, hint: 'Tem mais de 1,4 bilhões' },
  { id: 172, category: 'Geografia', difficulty: 'easy', question: 'Qual país tem a maior área?', options: ['Rússia', 'Canadá', 'China', 'EUA'], correctAnswer: 0, hint: 'Tem 17 milhões km²' },
  { id: 173, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país mais rico do mundo?', options: ['Luxemburgo', 'Suíça', 'Noruega', 'Catar'], correctAnswer: 0, hint: 'Por PIB per capita' },
  { id: 174, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país mais pobre do mundo?', options: ['Níger', 'Burundi', 'Chade', 'Mali'], correctAnswer: 0, hint: 'Por PIB per capita' },
  { id: 175, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país com mais idiomas?', options: ['Papua Nova Guiné', 'Indonésia', 'Nigéria', 'Índia'], correctAnswer: 0, hint: 'Tem mais de 800' },
  { id: 176, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país com mais religiões?', options: ['Índia', 'Indonésia', 'Nigéria', 'EUA'], correctAnswer: 0, hint: 'Tem muitas religiões' },
  { id: 177, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país com mais universidades?', options: ['EUA', 'China', 'Índia', 'Japão'], correctAnswer: 0, hint: 'Tem mais de 4.000' },
  { id: 178, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país com mais museus?', options: ['China', 'EUA', 'Itália', 'França'], correctAnswer: 0, hint: 'Tem mais de 5.000' },
  { id: 179, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país com mais parques nacionais?', options: ['Austrália', 'EUA', 'Canadá', 'Brasil'], correctAnswer: 0, hint: 'Tem mais de 600' },
  { id: 180, category: 'Geografia', difficulty: 'easy', question: 'Qual é o país com mais praias?', options: ['Indonésia', 'Filipinas', 'Brasil', 'Austrália'], correctAnswer: 0, hint: 'Tem mais de 17.000' },
  { id: 181, category: 'Geografia', difficulty: 'medium', question: 'Qual é o país com mais montanhas?', options: ['Indonésia', 'Filipinas', 'Japão', 'Tailândia'], correctAnswer: 0, hint: 'Tem mais de 130' },
  { id: 182, category: 'Geografia', difficulty: 'medium', question: 'Qual é o país com mais vulcões?', options: ['Indonésia', 'Japão', 'Filipinas', 'Chile'], correctAnswer: 0, hint: 'Tem mais de 130' },
  { id: 183, category: 'Geografia', difficulty: 'medium', question: 'Qual é o país com mais rios?', options: ['Rússia', 'Canadá', 'Brasil', 'China'], correctAnswer: 0, hint: 'Tem mais de 2 milhões' },
  { id: 184, category: 'Geografia', difficulty: 'medium', question: 'Qual é o país com mais lagos?', options: ['Canadá', 'Rússia', 'Finlândia', 'Suécia'], correctAnswer: 0, hint: 'Tem mais de 30.000' },
  { id: 185, category: 'Geografia', difficulty: 'medium', question: 'Qual é o país com mais ilhas?', options: ['Suécia', 'Noruega', 'Finlândia', 'Dinamarca'], correctAnswer: 0, hint: 'Tem mais de 50.000' },
  { id: 186, category: 'Geografia', difficulty: 'hard', question: 'Qual é o país com mais cidades?', options: ['China', 'Índia', 'EUA', 'Indonésia'], correctAnswer: 0, hint: 'Tem mais de 300' },
  { id: 187, category: 'Geografia', difficulty: 'hard', question: 'Qual é o país com mais estradas?', options: ['EUA', 'China', 'Índia', 'Rússia'], correctAnswer: 0, hint: 'Tem mais de 6 milhões km' },
  { id: 188, category: 'Geografia', difficulty: 'hard', question: 'Qual é o país com mais ferrovias?', options: ['Rússia', 'China', 'EUA', 'Índia'], correctAnswer: 0, hint: 'Tem mais de 86.000 km' },
  { id: 189, category: 'Geografia', difficulty: 'hard', question: 'Qual é o país com mais aeroportos?', options: ['EUA', 'China', 'Brasil', 'Índia'], correctAnswer: 0, hint: 'Tem mais de 5.000' },
  { id: 190, category: 'Geografia', difficulty: 'hard', question: 'Qual é o país com mais portos?', options: ['China', 'Índia', 'Indonésia', 'Filipinas'], correctAnswer: 0, hint: 'Tem mais de 2.000' },

  // HISTÓRIA - 50 perguntas
  { id: 191, category: 'História', difficulty: 'easy', question: 'Em que ano Cristóvão Colombo descobriu a América?', options: ['1492', '1500', '1485', '1510'], correctAnswer: 0, hint: 'Século XV' },
  { id: 192, category: 'História', difficulty: 'easy', question: 'Em que ano o Brasil foi descoberto?', options: ['1500', '1492', '1510', '1520'], correctAnswer: 0, hint: 'Por Cabral' },
  { id: 193, category: 'História', difficulty: 'easy', question: 'Quem foi o primeiro presidente do Brasil?', options: ['Deodoro da Fonseca', 'Floriano Peixoto', 'Prudente de Morais', 'Campos Sales'], correctAnswer: 0, hint: 'Proclamou a República' },
  { id: 194, category: 'História', difficulty: 'easy', question: 'Em que ano terminou a escravidão no Brasil?', options: ['1888', '1889', '1887', '1890'], correctAnswer: 0, hint: 'Lei Áurea' },
  { id: 195, category: 'História', difficulty: 'easy', question: 'Quem foi o primeiro imperador do Brasil?', options: ['Dom Pedro I', 'Dom Pedro II', 'Dom João VI', 'Dom José I'], correctAnswer: 0, hint: 'Proclamou a independência' },
  { id: 196, category: 'História', difficulty: 'easy', question: 'Em que ano o Brasil se tornou independente?', options: ['1822', '1821', '1823', '1824'], correctAnswer: 0, hint: 'Sete de Setembro' },
  { id: 197, category: 'História', difficulty: 'easy', question: 'Quem foi o primeiro presidente dos EUA?', options: ['George Washington', 'Thomas Jefferson', 'James Madison', 'James Monroe'], correctAnswer: 0, hint: 'Fundador da nação' },
  { id: 198, category: 'História', difficulty: 'easy', question: 'Em que ano os EUA se tornaram independentes?', options: ['1776', '1775', '1777', '1778'], correctAnswer: 0, hint: 'Declaração de Independência' },
  { id: 199, category: 'História', difficulty: 'easy', question: 'Quem foi o primeiro presidente da França?', options: ['Charles de Gaulle', 'Georges Clemenceau', 'Aristide Briand', 'Raymond Poincaré'], correctAnswer: 0, hint: 'Após a Segunda Guerra' },
  { id: 200, category: 'História', difficulty: 'easy', question: 'Em que ano a Revolução Francesa começou?', options: ['1789', '1788', '1790', '1791'], correctAnswer: 0, hint: 'Tomada da Bastilha' },
  { id: 201, category: 'História', difficulty: 'medium', question: 'Em que ano começou a Primeira Guerra Mundial?', options: ['1914', '1913', '1915', '1916'], correctAnswer: 0, hint: 'Assassinato do Arquiduque' },
  { id: 202, category: 'História', difficulty: 'medium', question: 'Em que ano terminou a Primeira Guerra Mundial?', options: ['1918', '1917', '1919', '1920'], correctAnswer: 0, hint: 'Armistício' },
  { id: 203, category: 'História', difficulty: 'medium', question: 'Em que ano começou a Segunda Guerra Mundial?', options: ['1939', '1938', '1940', '1941'], correctAnswer: 0, hint: 'Invasão da Polônia' },
  { id: 204, category: 'História', difficulty: 'medium', question: 'Em que ano terminou a Segunda Guerra Mundial?', options: ['1945', '1944', '1946', '1947'], correctAnswer: 0, hint: 'Rendição do Japão' },
  { id: 205, category: 'História', difficulty: 'medium', question: 'Quem foi o primeiro presidente da Rússia?', options: ['Boris Yeltsin', 'Mikhail Gorbachev', 'Leonid Brezhnev', 'Nikita Khrushchev'], correctAnswer: 0, hint: 'Após a União Soviética' },
  { id: 206, category: 'História', difficulty: 'hard', question: 'Em que ano caiu o Muro de Berlim?', options: ['1989', '1988', '1990', '1991'], correctAnswer: 0, hint: 'Fim da Guerra Fria' },
  { id: 207, category: 'História', difficulty: 'hard', question: 'Em que ano a União Soviética se dissolveu?', options: ['1991', '1990', '1992', '1993'], correctAnswer: 0, hint: 'Fim da URSS' },
  { id: 208, category: 'História', difficulty: 'hard', question: 'Quem foi o primeiro presidente da China?', options: ['Mao Zedong', 'Deng Xiaoping', 'Jiang Zemin', 'Hu Jintao'], correctAnswer: 0, hint: 'Fundou a República Popular' },
  { id: 209, category: 'História', difficulty: 'hard', question: 'Em que ano a China se tornou comunista?', options: ['1949', '1948', '1950', '1951'], correctAnswer: 0, hint: 'Revolução Chinesa' },
  { id: 210, category: 'História', difficulty: 'hard', question: 'Quem foi o primeiro presidente da Índia?', options: ['Jawaharlal Nehru', 'Rajendra Prasad', 'Sardar Vallabhbhai Patel', 'Mahatma Gandhi'], correctAnswer: 0, hint: 'Após a independência' },
  { id: 211, category: 'História', difficulty: 'easy', question: 'Quem foi Napoleão Bonaparte?', options: ['Imperador da França', 'Rei da Itália', 'Duque de Toscana', 'Príncipe de Córsega'], correctAnswer: 0, hint: 'Conquistador europeu' },
  { id: 212, category: 'História', difficulty: 'easy', question: 'Em que ano Napoleão foi derrotado em Waterloo?', options: ['1815', '1814', '1816', '1817'], correctAnswer: 0, hint: 'Fim de seu império' },
  { id: 213, category: 'História', difficulty: 'easy', question: 'Quem foi Júlio César?', options: ['Imperador Romano', 'Rei de Roma', 'Cônsul de Roma', 'Senador de Roma'], correctAnswer: 0, hint: 'Conquistador de Gália' },
  { id: 214, category: 'História', difficulty: 'easy', question: 'Em que ano Júlio César foi assassinado?', options: ['44 a.C.', '45 a.C.', '43 a.C.', '46 a.C.'], correctAnswer: 0, hint: 'Idos de Março' },
  { id: 215, category: 'História', difficulty: 'easy', question: 'Quem foi Cleópatra?', options: ['Rainha do Egito', 'Princesa de Roma', 'Imperatriz de Bizâncio', 'Rainha da Núbia'], correctAnswer: 0, hint: 'Última faraó' },
  { id: 216, category: 'História', difficulty: 'easy', question: 'Em que ano Cleópatra morreu?', options: ['30 a.C.', '31 a.C.', '29 a.C.', '32 a.C.'], correctAnswer: 0, hint: 'Suicídio' },
  { id: 217, category: 'História', difficulty: 'easy', question: 'Quem foi Genghis Khan?', options: ['Conquistador Mongol', 'Imperador Chinês', 'Rei da Pérsia', 'Sultão Turco'], correctAnswer: 0, hint: 'Fundador do Império Mongol' },
  { id: 218, category: 'História', difficulty: 'easy', question: 'Em que ano Genghis Khan morreu?', options: ['1227', '1226', '1228', '1229'], correctAnswer: 0, hint: 'Século XIII' },
  { id: 219, category: 'História', difficulty: 'easy', question: 'Quem foi Cristóvão Colombo?', options: ['Navegador Italiano', 'Explorador Espanhol', 'Navegador Português', 'Explorador Inglês'], correctAnswer: 0, hint: 'Descobriu a América' },
  { id: 220, category: 'História', difficulty: 'easy', question: 'Em que ano Colombo morreu?', options: ['1506', '1505', '1507', '1508'], correctAnswer: 0, hint: 'Século XVI' },
  { id: 221, category: 'História', difficulty: 'medium', question: 'Quem foi Vasco da Gama?', options: ['Navegador Português', 'Explorador Italiano', 'Navegador Espanhol', 'Explorador Inglês'], correctAnswer: 0, hint: 'Descobriu a rota para Índia' },
  { id: 222, category: 'História', difficulty: 'medium', question: 'Em que ano Vasco da Gama chegou à Índia?', options: ['1498', '1497', '1499', '1500'], correctAnswer: 0, hint: 'Rota do Cabo' },
  { id: 223, category: 'História', difficulty: 'medium', question: 'Quem foi Bartolomeu Dias?', options: ['Navegador Português', 'Explorador Italiano', 'Navegador Espanhol', 'Explorador Inglês'], correctAnswer: 0, hint: 'Descobriu o Cabo da Boa Esperança' },
  { id: 224, category: 'História', difficulty: 'medium', question: 'Em que ano Dias descobriu o Cabo?', options: ['1488', '1487', '1489', '1490'], correctAnswer: 0, hint: 'Século XV' },
  { id: 225, category: 'História', difficulty: 'medium', question: 'Quem foi Fernão de Magalhães?', options: ['Navegador Português', 'Explorador Italiano', 'Navegador Espanhol', 'Explorador Inglês'], correctAnswer: 0, hint: 'Primeira volta ao mundo' },
  { id: 226, category: 'História', difficulty: 'hard', question: 'Em que ano Magalhães iniciou sua viagem?', options: ['1519', '1518', '1520', '1521'], correctAnswer: 0, hint: 'Século XVI' },
  { id: 227, category: 'História', difficulty: 'hard', question: 'Quem foi Martim Afonso de Sousa?', options: ['Navegador Português', 'Conquistador Espanhol', 'Explorador Inglês', 'Navegador Italiano'], correctAnswer: 0, hint: 'Fundou São Vicente' },
  { id: 228, category: 'História', difficulty: 'hard', question: 'Em que ano Martim Afonso chegou ao Brasil?', options: ['1531', '1530', '1532', '1533'], correctAnswer: 0, hint: 'Século XVI' },
  { id: 229, category: 'História', difficulty: 'hard', question: 'Quem foi Tomás de Sousa?', options: ['Primeiro Governador-Geral', 'Navegador Português', 'Conquistador Espanhol', 'Explorador Inglês'], correctAnswer: 0, hint: 'Fundou Salvador' },
  { id: 230, category: 'História', difficulty: 'hard', question: 'Em que ano Tomás de Sousa chegou ao Brasil?', options: ['1549', '1548', '1550', '1551'], correctAnswer: 0, hint: 'Século XVI' },

  // PORTUGUÊS - 50 perguntas
  { id: 231, category: 'Português', difficulty: 'easy', question: 'Qual é o sinônimo de "feliz"?', options: ['Alegre', 'Triste', 'Nervoso', 'Cansado'], correctAnswer: 0, hint: 'Emoção positiva' },
  { id: 232, category: 'Português', difficulty: 'easy', question: 'Qual é o antônimo de "quente"?', options: ['Frio', 'Morno', 'Gelado', 'Fresco'], correctAnswer: 0, hint: 'Oposto' },
  { id: 233, category: 'Português', difficulty: 'easy', question: 'Qual é o plural de "livro"?', options: ['Livros', 'Livro', 'Livra', 'Livres'], correctAnswer: 0, hint: 'Mais de um' },
  { id: 234, category: 'Português', difficulty: 'easy', question: 'Qual é o feminino de "ator"?', options: ['Atriz', 'Atore', 'Atora', 'Atrice'], correctAnswer: 0, hint: 'Gênero feminino' },
  { id: 235, category: 'Português', difficulty: 'easy', question: 'Qual é o diminutivo de "casa"?', options: ['Casinha', 'Casita', 'Casinha', 'Caseta'], correctAnswer: 0, hint: 'Coisa pequena' },
  { id: 236, category: 'Português', difficulty: 'easy', question: 'Qual é o aumentativo de "gato"?', options: ['Gatão', 'Gatão', 'Gataço', 'Gatarão'], correctAnswer: 0, hint: 'Coisa grande' },
  { id: 237, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "Ele vai" ou "Ele vão"?', options: ['Ele vai', 'Ele vão', 'Ele vai', 'Ele vão'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 238, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "A menina correu" ou "A menina correram"?', options: ['A menina correu', 'A menina correram', 'A menina correu', 'A menina correram'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 239, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "Meu livro" ou "Meu livra"?', options: ['Meu livro', 'Meu livra', 'Meu livro', 'Meu livra'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 240, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "Ela é bonita" ou "Ela é bonito"?', options: ['Ela é bonita', 'Ela é bonito', 'Ela é bonita', 'Ela é bonito'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 241, category: 'Português', difficulty: 'medium', question: 'Qual é o sinônimo de "inteligente"?', options: ['Esperto', 'Burro', 'Lento', 'Preguiçoso'], correctAnswer: 0, hint: 'Pessoa com inteligência' },
  { id: 242, category: 'Português', difficulty: 'medium', question: 'Qual é o antônimo de "grande"?', options: ['Pequeno', 'Médio', 'Minúsculo', 'Gigante'], correctAnswer: 0, hint: 'Oposto' },
  { id: 243, category: 'Português', difficulty: 'medium', question: 'Qual é o plural de "pão"?', options: ['Pães', 'Pão', 'Pana', 'Panes'], correctAnswer: 0, hint: 'Mais de um' },
  { id: 244, category: 'Português', difficulty: 'medium', question: 'Qual é o feminino de "príncipe"?', options: ['Princesa', 'Príncipe', 'Príncipa', 'Principe'], correctAnswer: 0, hint: 'Gênero feminino' },
  { id: 245, category: 'Português', difficulty: 'medium', question: 'Qual é o diminutivo de "pé"?', options: ['Pezinho', 'Pezita', 'Pezeta', 'Pezeta'], correctAnswer: 0, hint: 'Coisa pequena' },
  { id: 246, category: 'Português', difficulty: 'hard', question: 'Qual é o aumentativo de "mão"?', options: ['Mãozão', 'Mãona', 'Mãota', 'Mãorra'], correctAnswer: 0, hint: 'Coisa grande' },
  { id: 247, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Nós vamos" ou "Nós vai"?', options: ['Nós vamos', 'Nós vai', 'Nós vamos', 'Nós vai'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 248, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Os meninos correram" ou "Os meninos correu"?', options: ['Os meninos correram', 'Os meninos correu', 'Os meninos correram', 'Os meninos correu'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 249, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Nossos livros" ou "Nossos livra"?', options: ['Nossos livros', 'Nossos livra', 'Nossos livros', 'Nossos livra'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 250, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Elas são bonitas" ou "Elas são bonito"?', options: ['Elas são bonitas', 'Elas são bonito', 'Elas são bonitas', 'Elas são bonito'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 251, category: 'Português', difficulty: 'easy', question: 'Qual é o sinônimo de "triste"?', options: ['Infeliz', 'Alegre', 'Nervoso', 'Cansado'], correctAnswer: 0, hint: 'Emoção negativa' },
  { id: 252, category: 'Português', difficulty: 'easy', question: 'Qual é o antônimo de "claro"?', options: ['Escuro', 'Brilhante', 'Luminoso', 'Transparente'], correctAnswer: 0, hint: 'Oposto' },
  { id: 253, category: 'Português', difficulty: 'easy', question: 'Qual é o plural de "flor"?', options: ['Flores', 'Flor', 'Flora', 'Flore'], correctAnswer: 0, hint: 'Mais de um' },
  { id: 254, category: 'Português', difficulty: 'easy', question: 'Qual é o feminino de "príncipe"?', options: ['Princesa', 'Príncipe', 'Príncipa', 'Principe'], correctAnswer: 0, hint: 'Gênero feminino' },
  { id: 255, category: 'Português', difficulty: 'easy', question: 'Qual é o diminutivo de "cão"?', options: ['Cãozinho', 'Cãozita', 'Cãozeta', 'Cãozeta'], correctAnswer: 0, hint: 'Coisa pequena' },
  { id: 256, category: 'Português', difficulty: 'easy', question: 'Qual é o aumentativo de "nariz"?', options: ['Narizão', 'Narizão', 'Narizota', 'Narizarra'], correctAnswer: 0, hint: 'Coisa grande' },
  { id: 257, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "Você vai" ou "Você vão"?', options: ['Você vai', 'Você vão', 'Você vai', 'Você vão'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 258, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "A criança dormiu" ou "A criança dormiram"?', options: ['A criança dormiu', 'A criança dormiram', 'A criança dormiu', 'A criança dormiram'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 259, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "Seu carro" ou "Seu carra"?', options: ['Seu carro', 'Seu carra', 'Seu carro', 'Seu carra'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 260, category: 'Português', difficulty: 'easy', question: 'Qual é a forma correta: "Ele é inteligente" ou "Ele é inteligenta"?', options: ['Ele é inteligente', 'Ele é inteligenta', 'Ele é inteligente', 'Ele é inteligenta'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 261, category: 'Português', difficulty: 'medium', question: 'Qual é o sinônimo de "medo"?', options: ['Pavor', 'Coragem', 'Ousadia', 'Confiança'], correctAnswer: 0, hint: 'Emoção negativa' },
  { id: 262, category: 'Português', difficulty: 'medium', question: 'Qual é o antônimo de "lindo"?', options: ['Feio', 'Bonito', 'Formoso', 'Belo'], correctAnswer: 0, hint: 'Oposto' },
  { id: 263, category: 'Português', difficulty: 'medium', question: 'Qual é o plural de "café"?', options: ['Cafés', 'Café', 'Cafa', 'Cafes'], correctAnswer: 0, hint: 'Mais de um' },
  { id: 264, category: 'Português', difficulty: 'medium', question: 'Qual é o feminino de "ator"?', options: ['Atriz', 'Atore', 'Atora', 'Atrice'], correctAnswer: 0, hint: 'Gênero feminino' },
  { id: 265, category: 'Português', difficulty: 'medium', question: 'Qual é o diminutivo de "gato"?', options: ['Gatinho', 'Gatita', 'Gateta', 'Gateta'], correctAnswer: 0, hint: 'Coisa pequena' },
  { id: 266, category: 'Português', difficulty: 'hard', question: 'Qual é o aumentativo de "olho"?', options: ['Olhão', 'Olhão', 'Olhota', 'Olharra'], correctAnswer: 0, hint: 'Coisa grande' },
  { id: 267, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Eles vão" ou "Eles vai"?', options: ['Eles vão', 'Eles vai', 'Eles vão', 'Eles vai'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 268, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "As meninas correram" ou "As meninas correu"?', options: ['As meninas correram', 'As meninas correu', 'As meninas correram', 'As meninas correu'], correctAnswer: 0, hint: 'Concordância verbal' },
  { id: 269, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Vossas casas" ou "Vossas casa"?', options: ['Vossas casas', 'Vossas casa', 'Vossas casas', 'Vossas casa'], correctAnswer: 0, hint: 'Concordância nominal' },
  { id: 270, category: 'Português', difficulty: 'hard', question: 'Qual é a forma correta: "Eles são altos" ou "Eles são alta"?', options: ['Eles são altos', 'Eles são alta', 'Eles são altos', 'Eles são alta'], correctAnswer: 0, hint: 'Concordância nominal' },

  // ESPORTES - 30 perguntas
  { id: 271, category: 'Esportes', difficulty: 'easy', question: 'Quantos jogadores tem um time de futebol em campo?', options: ['11', '10', '12', '9'], correctAnswer: 0, hint: 'Incluindo o goleiro' },
  { id: 272, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte mais popular do mundo?', options: ['Futebol', 'Basquete', 'Tênis', 'Críquete'], correctAnswer: 0, hint: 'Tem 4 bilhões de fãs' },
  { id: 273, category: 'Esportes', difficulty: 'easy', question: 'Quantos pontos vale um gol no futebol?', options: ['1', '2', '3', '0'], correctAnswer: 0, hint: 'Objetivo do jogo' },
  { id: 274, category: 'Esportes', difficulty: 'easy', question: 'Quantas rodadas tem um torneio de boxe profissional?', options: ['12', '10', '15', '8'], correctAnswer: 0, hint: 'Máximo' },
  { id: 275, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte com mais medalhas nas Olimpíadas?', options: ['Natação', 'Atletismo', 'Ginástica', 'Levantamento de peso'], correctAnswer: 0, hint: 'Tem mais de 30 eventos' },
  { id: 276, category: 'Esportes', difficulty: 'medium', question: 'Quantos sets tem um jogo de tênis?', options: ['3', '2', '4', '5'], correctAnswer: 0, hint: 'Melhor de 3' },
  { id: 277, category: 'Esportes', difficulty: 'medium', question: 'Qual é a duração de um jogo de basquete profissional?', options: ['48 minutos', '40 minutos', '45 minutos', '50 minutos'], correctAnswer: 0, hint: 'NBA' },
  { id: 278, category: 'Esportes', difficulty: 'medium', question: 'Quantos pontos vale um touchdown no futebol americano?', options: ['6', '7', '3', '2'], correctAnswer: 0, hint: 'Objetivo principal' },
  { id: 279, category: 'Esportes', difficulty: 'hard', question: 'Qual é a velocidade máxima de um saque no tênis profissional?', options: ['200+ km/h', '150 km/h', '180 km/h', '220 km/h'], correctAnswer: 0, hint: 'Recorde mundial' },
  { id: 280, category: 'Esportes', difficulty: 'hard', question: 'Quantos pontos vale um arremesso de 3 pontos no basquete?', options: ['3', '2', '1', '4'], correctAnswer: 0, hint: 'Além da linha' },
  { id: 281, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte praticado em uma piscina?', options: ['Natação', 'Futebol', 'Basquete', 'Tênis'], correctAnswer: 0, hint: 'Esporte aquático' },
  { id: 282, category: 'Esportes', difficulty: 'easy', question: 'Quantas rodadas tem um jogo de xadrez profissional?', options: ['Variável', '10', '20', '30'], correctAnswer: 0, hint: 'Depende do torneio' },
  { id: 283, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte com a bola mais pesada?', options: ['Boliche', 'Futebol', 'Basquete', 'Vôlei'], correctAnswer: 0, hint: 'Bola de 7 kg' },
  { id: 284, category: 'Esportes', difficulty: 'easy', question: 'Quantos jogadores tem um time de vôlei em campo?', options: ['6', '5', '7', '4'], correctAnswer: 0, hint: 'Por lado' },
  { id: 285, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte com mais medalhas no Brasil?', options: ['Vôlei', 'Futebol', 'Natação', 'Atletismo'], correctAnswer: 0, hint: 'Ouro olímpico' },
  { id: 286, category: 'Esportes', difficulty: 'medium', question: 'Qual é a duração de um jogo de futebol profissional?', options: ['90 minutos', '80 minutos', '100 minutos', '85 minutos'], correctAnswer: 0, hint: 'Mais acréscimos' },
  { id: 287, category: 'Esportes', difficulty: 'medium', question: 'Quantos pontos vale um gol de cabeça no futebol?', options: ['1', '2', '0', '3'], correctAnswer: 0, hint: 'Mesmo que chute' },
  { id: 288, category: 'Esportes', difficulty: 'medium', question: 'Qual é o esporte com mais participantes nas Olimpíadas?', options: ['Atletismo', 'Natação', 'Ginástica', 'Levantamento de peso'], correctAnswer: 0, hint: 'Tem mais de 40 eventos' },
  { id: 289, category: 'Esportes', difficulty: 'hard', question: 'Qual é a velocidade máxima de um saque no voleibol profissional?', options: ['120+ km/h', '100 km/h', '140 km/h', '150 km/h'], correctAnswer: 0, hint: 'Recorde mundial' },
  { id: 290, category: 'Esportes', difficulty: 'hard', question: 'Quantos pontos vale um gol de falta no futebol?', options: ['1', '2', '0', '3'], correctAnswer: 0, hint: 'Mesmo que gol normal' },
  { id: 291, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte praticado em um campo de grama?', options: ['Futebol', 'Basquete', 'Tênis', 'Vôlei'], correctAnswer: 0, hint: 'Esporte popular' },
  { id: 292, category: 'Esportes', difficulty: 'easy', question: 'Quantas rodadas tem um jogo de damas?', options: ['Variável', '10', '20', '30'], correctAnswer: 0, hint: 'Depende do jogo' },
  { id: 293, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte com a bola mais leve?', options: ['Badminton', 'Futebol', 'Basquete', 'Vôlei'], correctAnswer: 0, hint: 'Peteca' },
  { id: 294, category: 'Esportes', difficulty: 'easy', question: 'Quantos jogadores tem um time de hóquei no gelo?', options: ['6', '5', '7', '4'], correctAnswer: 0, hint: 'Por lado' },
  { id: 295, category: 'Esportes', difficulty: 'easy', question: 'Qual é o esporte com mais medalhas de ouro no Brasil?', options: ['Vôlei', 'Futebol', 'Natação', 'Atletismo'], correctAnswer: 0, hint: 'Feminino' },
  { id: 296, category: 'Esportes', difficulty: 'medium', question: 'Qual é a duração de um jogo de hóquei no gelo profissional?', options: ['60 minutos', '45 minutos', '90 minutos', '80 minutos'], correctAnswer: 0, hint: '3 períodos' },
  { id: 297, category: 'Esportes', difficulty: 'medium', question: 'Quantos pontos vale um gol em um jogo de hóquei?', options: ['1', '2', '0', '3'], correctAnswer: 0, hint: 'Objetivo' },
  { id: 298, category: 'Esportes', difficulty: 'medium', question: 'Qual é o esporte com mais participantes nas Olimpíadas de Inverno?', options: ['Esqui', 'Patinação', 'Hóquei', 'Curling'], correctAnswer: 0, hint: 'Tem mais de 10 eventos' },
  { id: 299, category: 'Esportes', difficulty: 'hard', question: 'Qual é a velocidade máxima de um arremesso de beisebol profissional?', options: ['160+ km/h', '140 km/h', '180 km/h', '200 km/h'], correctAnswer: 0, hint: 'Recorde mundial' },
  { id: 300, category: 'Esportes', difficulty: 'hard', question: 'Quantos pontos vale um home run no beisebol?', options: ['4', '3', '2', '1'], correctAnswer: 0, hint: 'Volta completa' },
];

export function getQuestionsByDifficulty(difficulty: 'easy' | 'medium' | 'hard'): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter(q => q.difficulty === difficulty);
}

export function getQuestionsByCategory(category: string): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter(q => q.category === category);
}

export function getQuestionsByDifficultyAndCategory(difficulty: 'easy' | 'medium' | 'hard', category: string): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter(q => q.difficulty === difficulty && q.category === category);
}

export function getRandomQuestions(count: number, difficulty?: 'easy' | 'medium' | 'hard'): QuizQuestion[] {
  let questions = QUIZ_QUESTIONS;
  if (difficulty) {
    questions = getQuestionsByDifficulty(difficulty);
  }
  
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function shuffleQuestions(questions: QuizQuestion[]): QuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5);
}

export function shuffleOptions(question: QuizQuestion): QuizQuestion {
  const indices = [0, 1, 2, 3];
  const shuffledIndices = indices.sort(() => Math.random() - 0.5);
  const newCorrectAnswerIndex = shuffledIndices.indexOf(question.correctAnswer);
  const shuffledOptions = shuffledIndices.map(i => question.options[i]);
  return {
    ...question,
    options: shuffledOptions,
    correctAnswer: newCorrectAnswerIndex
  };
}
