export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  hint: string;
  emoji?: string;
  animeImage?: number; // 1-5 referência às imagens de anime
}

export const quizQuestionsExpanded: Question[] = [
  // Perguntas sobre Animes e Mangá (1-30)
  {
    id: 1,
    question: "Qual é o nome do protagonista de Naruto?",
    options: ["Sasuke", "Naruto Uzumaki", "Kakashi", "Sakura"],
    correctAnswer: 1,
    hint: "É um ninja com cabelos loiros.",
    emoji: "🥷",
    animeImage: 1,
  },
  {
    id: 2,
    question: "Em Dragon Ball, qual é o nome do personagem principal?",
    options: ["Vegeta", "Goku", "Freezer", "Krillin"],
    correctAnswer: 1,
    hint: "Ele adora comer e treinar.",
    emoji: "⚡",
    animeImage: 4,
  },
  {
    id: 3,
    question: "Qual é o nome da espada de Ichigo em Bleach?",
    options: ["Zangetsu", "Senbonzakura", "Kyoka Suigetsu", "Tensa Zangetsu"],
    correctAnswer: 0,
    hint: "Significa 'lua cortante'.",
    emoji: "⚔️",
    animeImage: 4,
  },
  {
    id: 4,
    question: "Em One Piece, qual é o nome do capitão dos Piratas do Chapéu de Palha?",
    options: ["Zoro", "Luffy", "Nami", "Sanji"],
    correctAnswer: 1,
    hint: "Ele quer ser o Rei dos Piratas.",
    emoji: "🏴‍☠️",
    animeImage: 1,
  },
  {
    id: 5,
    question: "Qual é o nome do Titan Colossal em Attack on Titan?",
    options: ["Eren", "Armored Titan", "Colossal Titan", "Beast Titan"],
    correctAnswer: 2,
    hint: "É o maior dos Titãs.",
    emoji: "👹",
    animeImage: 4,
  },
  {
    id: 6,
    question: "Em My Hero Academia, qual é o nome do protagonista?",
    options: ["Bakugo", "Deku", "All Might", "Todoroki"],
    correctAnswer: 1,
    hint: "Ele é um herói sem poderes inicialmente.",
    emoji: "🦸",
    animeImage: 1,
  },
  {
    id: 7,
    question: "Qual é o nome do Shinigami em Death Note?",
    options: ["Light", "L", "Ryuk", "Misa"],
    correctAnswer: 2,
    hint: "É um deus da morte que adora maçãs.",
    emoji: "💀",
    animeImage: 2,
  },
  {
    id: 8,
    question: "Em Demon Slayer, qual é o nome do protagonista?",
    options: ["Tanjiro", "Nezuko", "Giyu", "Rengoku"],
    correctAnswer: 0,
    hint: "Ele tem uma irmã que é um demônio.",
    emoji: "🗡️",
    animeImage: 1,
  },
  {
    id: 9,
    question: "Qual é o nome da Rainha em Sailor Moon?",
    options: ["Usagi", "Rei", "Ami", "Makoto"],
    correctAnswer: 0,
    hint: "Ela é a Sailor Moon.",
    emoji: "🌙",
    animeImage: 3,
  },
  {
    id: 10,
    question: "Em Jujutsu Kaisen, qual é o nome do protagonista?",
    options: ["Megumi", "Yuji", "Gojo", "Sukuna"],
    correctAnswer: 1,
    hint: "Ele engoliu um dedo de um demônio poderoso.",
    emoji: "👹",
    animeImage: 4,
  },

  // Perguntas sobre Matemática (11-50)
  {
    id: 11,
    question: "Quanto é 5 + 7?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    hint: "Conte nos dedos.",
    emoji: "🔢",
  },
  {
    id: 12,
    question: "Quanto é 10 - 3?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 2,
    hint: "Comece com 10 e tire 3.",
    emoji: "🔢",
  },
  {
    id: 13,
    question: "Quanto é 3 × 4?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    hint: "3 grupos de 4.",
    emoji: "🔢",
  },
  {
    id: 14,
    question: "Quanto é 20 ÷ 5?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 1,
    hint: "Quantas vezes 5 cabe em 20?",
    emoji: "🔢",
  },
  {
    id: 15,
    question: "Qual é o dobro de 8?",
    options: ["14", "15", "16", "17"],
    correctAnswer: 2,
    hint: "8 + 8 = ?",
    emoji: "🔢",
  },
  {
    id: 16,
    question: "Qual é a metade de 14?",
    options: ["6", "7", "8", "9"],
    correctAnswer: 1,
    hint: "14 dividido por 2.",
    emoji: "🔢",
  },
  {
    id: 17,
    question: "Quanto é 6 + 6 + 6?",
    options: ["16", "17", "18", "19"],
    correctAnswer: 2,
    hint: "Três vezes 6.",
    emoji: "🔢",
  },
  {
    id: 18,
    question: "Qual número vem depois de 99?",
    options: ["98", "100", "101", "102"],
    correctAnswer: 1,
    hint: "É um número redondo.",
    emoji: "🔢",
  },
  {
    id: 19,
    question: "Quanto é 15 + 15?",
    options: ["28", "29", "30", "31"],
    correctAnswer: 2,
    hint: "Dois grupos de 15.",
    emoji: "🔢",
  },
  {
    id: 20,
    question: "Qual é o triplo de 5?",
    options: ["12", "13", "15", "16"],
    correctAnswer: 2,
    hint: "5 + 5 + 5 = ?",
    emoji: "🔢",
  },
  {
    id: 21,
    question: "Quanto é 9 × 2?",
    options: ["16", "17", "18", "19"],
    correctAnswer: 2,
    hint: "Duas vezes 9.",
    emoji: "🔢",
  },
  {
    id: 22,
    question: "Quanto é 25 - 10?",
    options: ["13", "14", "15", "16"],
    correctAnswer: 2,
    hint: "Comece com 25 e tire 10.",
    emoji: "🔢",
  },
  {
    id: 23,
    question: "Qual é o quádruplo de 3?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    hint: "3 × 4 = ?",
    emoji: "🔢",
  },
  {
    id: 24,
    question: "Quanto é 7 + 8?",
    options: ["14", "15", "16", "17"],
    correctAnswer: 1,
    hint: "Conte nos dedos.",
    emoji: "🔢",
  },
  {
    id: 25,
    question: "Quanto é 30 ÷ 6?",
    options: ["4", "5", "6", "7"],
    correctAnswer: 1,
    hint: "Quantas vezes 6 cabe em 30?",
    emoji: "🔢",
  },
  {
    id: 26,
    question: "Qual número é maior: 47 ou 74?",
    options: ["47", "74", "São iguais", "Não dá para saber"],
    correctAnswer: 1,
    hint: "O 7 está na casa das dezenas em um deles.",
    emoji: "🔢",
  },
  {
    id: 27,
    question: "Quanto é 11 + 11?",
    options: ["20", "21", "22", "23"],
    correctAnswer: 2,
    hint: "Dois grupos de 11.",
    emoji: "🔢",
  },
  {
    id: 28,
    question: "Quanto é 50 - 25?",
    options: ["20", "22", "24", "25"],
    correctAnswer: 3,
    hint: "Metade de 50.",
    emoji: "🔢",
  },
  {
    id: 29,
    question: "Qual é a quinta parte de 25?",
    options: ["4", "5", "6", "7"],
    correctAnswer: 1,
    hint: "25 ÷ 5 = ?",
    emoji: "🔢",
  },
  {
    id: 30,
    question: "Quanto é 4 × 5?",
    options: ["18", "19", "20", "21"],
    correctAnswer: 2,
    hint: "4 grupos de 5.",
    emoji: "🔢",
  },

  // Perguntas sobre Ciências (31-70)
  {
    id: 31,
    question: "Quantos planetas tem o sistema solar?",
    options: ["7", "8", "9", "10"],
    correctAnswer: 1,
    hint: "Plutão não é mais considerado planeta.",
    emoji: "🪐",
  },
  {
    id: 32,
    question: "Qual é o maior planeta do sistema solar?",
    options: ["Saturno", "Netuno", "Júpiter", "Marte"],
    correctAnswer: 2,
    hint: "Começa com J.",
    emoji: "🪐",
  },
  {
    id: 33,
    question: "Qual é o planeta mais próximo do Sol?",
    options: ["Vênus", "Mercúrio", "Terra", "Marte"],
    correctAnswer: 1,
    hint: "É o menor planeta.",
    emoji: "☀️",
  },
  {
    id: 34,
    question: "Qual é o nome do nosso planeta?",
    options: ["Marte", "Terra", "Vênus", "Júpiter"],
    correctAnswer: 1,
    hint: "É onde vivemos.",
    emoji: "🌍",
  },
  {
    id: 35,
    question: "Quantas luas tem a Terra?",
    options: ["0", "1", "2", "3"],
    correctAnswer: 1,
    hint: "Você a vê à noite.",
    emoji: "🌙",
  },
  {
    id: 36,
    question: "Qual é o maior animal do mundo?",
    options: ["Elefante", "Baleia azul", "Girafa", "Rinoceronte"],
    correctAnswer: 1,
    hint: "Vive no oceano.",
    emoji: "🐋",
  },
  {
    id: 37,
    question: "Quantos ossos tem um adulto?",
    options: ["150", "206", "250", "300"],
    correctAnswer: 1,
    hint: "Mais de 200.",
    emoji: "🦴",
  },
  {
    id: 38,
    question: "Qual é o órgão mais importante do corpo?",
    options: ["Pulmão", "Coração", "Cérebro", "Estômago"],
    correctAnswer: 1,
    hint: "Bombeia sangue.",
    emoji: "❤️",
  },
  {
    id: 39,
    question: "Qual é a cor do sangue?",
    options: ["Azul", "Verde", "Vermelho", "Amarelo"],
    correctAnswer: 2,
    hint: "É a cor do fogo.",
    emoji: "🩸",
  },
  {
    id: 40,
    question: "Quantos dedos tem um ser humano?",
    options: ["8", "9", "10", "12"],
    correctAnswer: 2,
    hint: "5 em cada mão.",
    emoji: "✋",
  },
  {
    id: 41,
    question: "Qual é o gás que respiramos?",
    options: ["Nitrogênio", "Oxigênio", "Hélio", "Argônio"],
    correctAnswer: 1,
    hint: "Começa com O.",
    emoji: "💨",
  },
  {
    id: 42,
    question: "Qual é a maior floresta do mundo?",
    options: ["Floresta Negra", "Floresta Amazônica", "Floresta Boreal", "Floresta Tropical"],
    correctAnswer: 1,
    hint: "Fica na América do Sul.",
    emoji: "🌳",
  },
  {
    id: 43,
    question: "Quantos continentes tem a Terra?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 2,
    hint: "Mais de 6.",
    emoji: "🌍",
  },
  {
    id: 44,
    question: "Qual é o oceano mais profundo?",
    options: ["Oceano Atlântico", "Oceano Pacífico", "Oceano Índico", "Oceano Ártico"],
    correctAnswer: 1,
    hint: "É o maior oceano.",
    emoji: "🌊",
  },
  {
    id: 45,
    question: "Qual é a montanha mais alta do mundo?",
    options: ["K2", "Everest", "Kilimanjaro", "Aconcágua"],
    correctAnswer: 1,
    hint: "Fica no Himalaia.",
    emoji: "⛰️",
  },
  {
    id: 46,
    question: "Qual é o animal mais rápido do mundo?",
    options: ["Leão", "Gazela", "Guepardo", "Avestruz"],
    correctAnswer: 2,
    hint: "É um felino.",
    emoji: "🐆",
  },
  {
    id: 47,
    question: "Quantas espécies de animais existem?",
    options: ["Milhões", "Bilhões", "Trilhões", "Milhares"],
    correctAnswer: 0,
    hint: "É um número muito grande.",
    emoji: "🦁",
  },
  {
    id: 48,
    question: "Qual é a temperatura do corpo humano?",
    options: ["35°C", "36°C", "37°C", "38°C"],
    correctAnswer: 2,
    hint: "Aproximadamente 37.",
    emoji: "🌡️",
  },
  {
    id: 49,
    question: "Qual é o animal que dorme em pé?",
    options: ["Gato", "Cavalo", "Cachorro", "Pássaro"],
    correctAnswer: 1,
    hint: "É um animal grande.",
    emoji: "🐴",
  },
  {
    id: 50,
    question: "Qual é o animal que voa mais alto?",
    options: ["Águia", "Pombo", "Condor", "Falcão"],
    correctAnswer: 2,
    hint: "É um pássaro muito grande.",
    emoji: "🦅",
  },

  // Perguntas sobre Geografia (51-90)
  {
    id: 51,
    question: "Qual é a capital do Brasil?",
    options: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
    correctAnswer: 2,
    hint: "É uma cidade planejada.",
    emoji: "🏛️",
  },
  {
    id: 52,
    question: "Qual é a capital da França?",
    options: ["Lyon", "Marselha", "Paris", "Toulouse"],
    correctAnswer: 2,
    hint: "Tem a Torre Eiffel.",
    emoji: "🗼",
  },
  {
    id: 53,
    question: "Qual é a capital do Japão?",
    options: ["Osaka", "Kyoto", "Tóquio", "Yokohama"],
    correctAnswer: 2,
    hint: "É a maior cidade do Japão.",
    emoji: "🗾",
  },
  {
    id: 54,
    question: "Qual é a capital dos EUA?",
    options: ["Nova York", "Los Angeles", "Washington", "Chicago"],
    correctAnswer: 2,
    hint: "Tem a Casa Branca.",
    emoji: "🏛️",
  },
  {
    id: 55,
    question: "Qual é a capital da Itália?",
    options: ["Milão", "Veneza", "Roma", "Florença"],
    correctAnswer: 2,
    hint: "Tem o Coliseu.",
    emoji: "🏛️",
  },
  {
    id: 56,
    question: "Qual é a capital da Espanha?",
    options: ["Barcelona", "Valencia", "Madri", "Sevilha"],
    correctAnswer: 2,
    hint: "Começa com M.",
    emoji: "🇪🇸",
  },
  {
    id: 57,
    question: "Qual é a capital da Alemanha?",
    options: ["Munique", "Hamburgo", "Berlim", "Colônia"],
    correctAnswer: 2,
    hint: "Começa com B.",
    emoji: "🇩🇪",
  },
  {
    id: 58,
    question: "Qual é a capital da Inglaterra?",
    options: ["Manchester", "Liverpool", "Londres", "Birmingham"],
    correctAnswer: 2,
    hint: "Tem o Big Ben.",
    emoji: "🇬🇧",
  },
  {
    id: 59,
    question: "Qual é a capital da Austrália?",
    options: ["Sydney", "Melbourne", "Camberra", "Brisbane"],
    correctAnswer: 2,
    hint: "Não é Sydney.",
    emoji: "🇦🇺",
  },
  {
    id: 60,
    question: "Qual é a capital do Canadá?",
    options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    correctAnswer: 2,
    hint: "Começa com O.",
    emoji: "🇨🇦",
  },
  {
    id: 61,
    question: "Qual é o país mais populoso do mundo?",
    options: ["Índia", "EUA", "China", "Brasil"],
    correctAnswer: 2,
    hint: "Tem a Grande Muralha.",
    emoji: "🇨🇳",
  },
  {
    id: 62,
    question: "Qual é o país mais rico do mundo?",
    options: ["EUA", "China", "Japão", "Alemanha"],
    correctAnswer: 0,
    hint: "Começa com E.",
    emoji: "💰",
  },
  {
    id: 63,
    question: "Qual é o rio mais longo do mundo?",
    options: ["Amazonas", "Nilo", "Iangtze", "Mississípi"],
    correctAnswer: 1,
    hint: "Fica na África.",
    emoji: "🌊",
  },
  {
    id: 64,
    question: "Qual é o deserto mais quente do mundo?",
    options: ["Deserto de Gobi", "Deserto de Kalahari", "Deserto do Saara", "Deserto de Atacama"],
    correctAnswer: 2,
    hint: "Fica na África.",
    emoji: "🏜️",
  },
  {
    id: 65,
    question: "Qual é a floresta tropical maior do mundo?",
    options: ["Floresta de Bornéu", "Floresta do Congo", "Floresta Amazônica", "Floresta Daintree"],
    correctAnswer: 2,
    hint: "Fica na América do Sul.",
    emoji: "🌳",
  },
  {
    id: 66,
    question: "Qual é o país com mais ilhas?",
    options: ["Filipinas", "Indonésia", "Suécia", "Noruega"],
    correctAnswer: 1,
    hint: "Tem milhares de ilhas.",
    emoji: "🏝️",
  },
  {
    id: 67,
    question: "Qual é o país mais frio do mundo?",
    options: ["Canadá", "Rússia", "Antártida", "Groenlândia"],
    correctAnswer: 2,
    hint: "É um continente.",
    emoji: "❄️",
  },
  {
    id: 68,
    question: "Qual é o país mais quente do mundo?",
    options: ["Egito", "Iraque", "Kuait", "Arábia Saudita"],
    correctAnswer: 2,
    hint: "Fica no Oriente Médio.",
    emoji: "🔥",
  },
  {
    id: 69,
    question: "Qual é o país com mais vulcões?",
    options: ["Indonésia", "Filipinas", "Japão", "Chile"],
    correctAnswer: 0,
    hint: "Fica na Ásia.",
    emoji: "🌋",
  },
  {
    id: 70,
    question: "Qual é o país com mais fusos horários?",
    options: ["Rússia", "China", "França", "EUA"],
    correctAnswer: 2,
    hint: "Tem muitas ilhas espalhadas pelo mundo.",
    emoji: "⏰",
  },

  // Perguntas sobre História (71-110)
  {
    id: 71,
    question: "Em que ano o Brasil foi descoberto?",
    options: ["1490", "1500", "1510", "1520"],
    correctAnswer: 1,
    hint: "Começa com 15.",
    emoji: "🇧🇷",
  },
  {
    id: 72,
    question: "Quem descobriu o Brasil?",
    options: ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Bartolomeu Dias"],
    correctAnswer: 1,
    hint: "Tem Cabral no sobrenome.",
    emoji: "⛵",
  },
  {
    id: 73,
    question: "Qual foi o primeiro presidente do Brasil?",
    options: ["Getúlio Vargas", "Deodoro da Fonseca", "Floriano Peixoto", "Prudente de Morais"],
    correctAnswer: 1,
    hint: "Tem Fonseca no sobrenome.",
    emoji: "🎩",
  },
  {
    id: 74,
    question: "Em que ano terminou a Segunda Guerra Mundial?",
    options: ["1943", "1944", "1945", "1946"],
    correctAnswer: 2,
    hint: "Começa com 19.",
    emoji: "⚔️",
  },
  {
    id: 75,
    question: "Qual foi o primeiro homem a pisar na Lua?",
    options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Yuri Gagarin"],
    correctAnswer: 1,
    hint: "Tem Armstrong no sobrenome.",
    emoji: "🌙",
  },
  {
    id: 76,
    question: "Em que ano o homem pisou na Lua?",
    options: ["1967", "1968", "1969", "1970"],
    correctAnswer: 2,
    hint: "Começa com 196.",
    emoji: "🚀",
  },
  {
    id: 77,
    question: "Qual foi a primeira civilização do mundo?",
    options: ["Egípcia", "Mesopotâmica", "Grega", "Romana"],
    correctAnswer: 1,
    hint: "Fica entre o Tigre e o Eufrates.",
    emoji: "🏛️",
  },
  {
    id: 78,
    question: "Qual foi o primeiro imperador do Brasil?",
    options: ["Pedro II", "Pedro I", "João VI", "José I"],
    correctAnswer: 1,
    hint: "Tem I no nome.",
    emoji: "👑",
  },
  {
    id: 79,
    question: "Em que ano o Brasil se tornou independente?",
    options: ["1820", "1822", "1824", "1826"],
    correctAnswer: 1,
    hint: "Começa com 18.",
    emoji: "🇧🇷",
  },
  {
    id: 80,
    question: "Qual foi a primeira capital do Brasil?",
    options: ["Rio de Janeiro", "Salvador", "Brasília", "São Luís"],
    correctAnswer: 1,
    hint: "Fica na Bahia.",
    emoji: "🏛️",
  },
  {
    id: 81,
    question: "Quantos presidentes o Brasil já teve?",
    options: ["40", "45", "50", "55"],
    correctAnswer: 1,
    hint: "Mais de 40.",
    emoji: "🎩",
  },
  {
    id: 82,
    question: "Em que ano terminou a escravidão no Brasil?",
    options: ["1880", "1885", "1888", "1890"],
    correctAnswer: 2,
    hint: "Começa com 188.",
    emoji: "🔗",
  },
  {
    id: 83,
    question: "Qual foi o maior império da história?",
    options: ["Império Romano", "Império Britânico", "Império Mongol", "Império Persa"],
    correctAnswer: 1,
    hint: "Tinha colônias em vários continentes.",
    emoji: "🌍",
  },
  {
    id: 84,
    question: "Quantos anos durou o Império Romano?",
    options: ["500", "1000", "1500", "2000"],
    correctAnswer: 1,
    hint: "Mais de 1000 anos.",
    emoji: "🏛️",
  },
  {
    id: 85,
    question: "Qual foi a primeira universidade do Brasil?",
    options: ["USP", "UFRJ", "UFMG", "Universidade de São Paulo"],
    correctAnswer: 1,
    hint: "Fica no Rio de Janeiro.",
    emoji: "🎓",
  },
  {
    id: 86,
    question: "Em que ano foi proclamada a República no Brasil?",
    options: ["1885", "1888", "1889", "1891"],
    correctAnswer: 2,
    hint: "Começa com 188.",
    emoji: "🇧🇷",
  },
  {
    id: 87,
    question: "Qual foi o primeiro rei de Portugal?",
    options: ["Afonso I", "João I", "Manuel I", "Sebastião"],
    correctAnswer: 0,
    hint: "Tem Afonso no nome.",
    emoji: "👑",
  },
  {
    id: 88,
    question: "Quantos séculos tem um milênio?",
    options: ["5", "10", "15", "20"],
    correctAnswer: 1,
    hint: "Cada século tem 100 anos.",
    emoji: "📅",
  },
  {
    id: 89,
    question: "Em que século estamos?",
    options: ["20º", "21º", "22º", "23º"],
    correctAnswer: 1,
    hint: "Começou em 2000.",
    emoji: "📅",
  },
  {
    id: 90,
    question: "Qual foi a primeira revolução industrial?",
    options: ["Na Itália", "Na Inglaterra", "Na França", "Na Alemanha"],
    correctAnswer: 1,
    hint: "Começou com a mecanização.",
    emoji: "🏭",
  },

  // Perguntas sobre Português (91-130)
  {
    id: 91,
    question: "Qual é o sinônimo de 'feliz'?",
    options: ["Triste", "Alegre", "Cansado", "Assustado"],
    correctAnswer: 1,
    hint: "É o oposto de triste.",
    emoji: "😊",
  },
  {
    id: 92,
    question: "Qual é o antônimo de 'grande'?",
    options: ["Pequeno", "Enorme", "Gigante", "Imenso"],
    correctAnswer: 0,
    hint: "É o oposto.",
    emoji: "📏",
  },
  {
    id: 93,
    question: "Qual é o plural de 'gato'?",
    options: ["Gatos", "Gatão", "Gataço", "Gatinhos"],
    correctAnswer: 0,
    hint: "Adicione 's'.",
    emoji: "🐱",
  },
  {
    id: 94,
    question: "Qual é o singular de 'crianças'?",
    options: ["Criança", "Criançinha", "Criançaço", "Criançada"],
    correctAnswer: 0,
    hint: "Remova o 's'.",
    emoji: "👧",
  },
  {
    id: 95,
    question: "Qual é o verbo no infinitivo?",
    options: ["Correndo", "Correr", "Corro", "Corri"],
    correctAnswer: 1,
    hint: "Termina em 'r'.",
    emoji: "🏃",
  },
  {
    id: 96,
    question: "Qual é o tempo verbal do 'corri'?",
    options: ["Presente", "Passado", "Futuro", "Condicional"],
    correctAnswer: 1,
    hint: "Já aconteceu.",
    emoji: "⏰",
  },
  {
    id: 97,
    question: "Qual é o adjetivo na frase 'A casa vermelha'?",
    options: ["Casa", "Vermelha", "A", "Da"],
    correctAnswer: 1,
    hint: "Descreve a casa.",
    emoji: "🏠",
  },
  {
    id: 98,
    question: "Qual é o substantivo na frase 'O gato preto'?",
    options: ["O", "Gato", "Preto", "Da"],
    correctAnswer: 1,
    hint: "É a coisa.",
    emoji: "🐱",
  },
  {
    id: 99,
    question: "Quantas vogais tem o alfabeto?",
    options: ["3", "4", "5", "6"],
    correctAnswer: 2,
    hint: "A, E, I, O, U.",
    emoji: "🔤",
  },
  {
    id: 100,
    question: "Qual é a primeira letra do alfabeto?",
    options: ["B", "A", "C", "D"],
    correctAnswer: 1,
    hint: "Começa com A.",
    emoji: "🔤",
  },
  {
    id: 101,
    question: "Qual é a última letra do alfabeto?",
    options: ["X", "Y", "Z", "W"],
    correctAnswer: 2,
    hint: "Termina com Z.",
    emoji: "🔤",
  },
  {
    id: 102,
    question: "Quantas letras tem o alfabeto português?",
    options: ["24", "25", "26", "27"],
    correctAnswer: 2,
    hint: "Mais de 25.",
    emoji: "🔤",
  },
  {
    id: 103,
    question: "Qual é o sinônimo de 'bonito'?",
    options: ["Feio", "Lindo", "Horrível", "Desagradável"],
    correctAnswer: 1,
    hint: "É o oposto de feio.",
    emoji: "😍",
  },
  {
    id: 104,
    question: "Qual é o antônimo de 'quente'?",
    options: ["Morno", "Frio", "Gelado", "Congelado"],
    correctAnswer: 1,
    hint: "É o oposto.",
    emoji: "❄️",
  },
  {
    id: 105,
    question: "Qual é o diminutivo de 'casa'?",
    options: ["Casão", "Casinha", "Casaço", "Casarão"],
    correctAnswer: 1,
    hint: "Adicione 'inha'.",
    emoji: "🏠",
  },
  {
    id: 106,
    question: "Qual é o aumentativo de 'livro'?",
    options: ["Livrim", "Livrinho", "Livrão", "Livreco"],
    correctAnswer: 2,
    hint: "Adicione 'ão'.",
    emoji: "📖",
  },
  {
    id: 107,
    question: "Qual é o gênero do substantivo 'maçã'?",
    options: ["Masculino", "Feminino", "Neutro", "Indefinido"],
    correctAnswer: 1,
    hint: "Tem 'a' no final.",
    emoji: "🍎",
  },
  {
    id: 108,
    question: "Qual é o gênero do substantivo 'livro'?",
    options: ["Masculino", "Feminino", "Neutro", "Indefinido"],
    correctAnswer: 0,
    hint: "Tem 'o' no final.",
    emoji: "📖",
  },
  {
    id: 109,
    question: "Qual é o número do substantivo 'crianças'?",
    options: ["Singular", "Plural", "Dual", "Indefinido"],
    correctAnswer: 1,
    hint: "Tem mais de uma.",
    emoji: "👧",
  },
  {
    id: 110,
    question: "Qual é o número do substantivo 'gato'?",
    options: ["Singular", "Plural", "Dual", "Indefinido"],
    correctAnswer: 0,
    hint: "Tem apenas um.",
    emoji: "🐱",
  },

  // Perguntas sobre Esportes (111-150)
  {
    id: 111,
    question: "Quantos jogadores tem um time de futebol?",
    options: ["9", "10", "11", "12"],
    correctAnswer: 2,
    hint: "Mais de 10.",
    emoji: "⚽",
  },
  {
    id: 112,
    question: "Qual é o esporte mais popular do mundo?",
    options: ["Basquete", "Futebol", "Tênis", "Vôlei"],
    correctAnswer: 1,
    hint: "Tem bola redonda.",
    emoji: "⚽",
  },
  {
    id: 113,
    question: "Quantos pontos vale um touchdown no futebol americano?",
    options: ["3", "5", "6", "7"],
    correctAnswer: 2,
    hint: "Mais de 5.",
    emoji: "🏈",
  },
  {
    id: 114,
    question: "Quantos sets tem um jogo de tênis?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    hint: "Geralmente 3.",
    emoji: "🎾",
  },
  {
    id: 115,
    question: "Qual é o esporte praticado em piscina?",
    options: ["Surfe", "Natação", "Mergulho", "Vela"],
    correctAnswer: 1,
    hint: "Você nada.",
    emoji: "🏊",
  },
  {
    id: 116,
    question: "Quantas rodas tem uma bicicleta?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    hint: "Duas.",
    emoji: "🚴",
  },
  {
    id: 117,
    question: "Qual é o esporte praticado em quadra?",
    options: ["Surfe", "Basquete", "Esqui", "Escalada"],
    correctAnswer: 1,
    hint: "Tem bola de laranja.",
    emoji: "🏀",
  },
  {
    id: 118,
    question: "Quantos jogadores tem um time de vôlei?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 1,
    hint: "Seis.",
    emoji: "🏐",
  },
  {
    id: 119,
    question: "Qual é o esporte praticado em montanha?",
    options: ["Esqui", "Surfe", "Natação", "Golfe"],
    correctAnswer: 0,
    hint: "Tem neve.",
    emoji: "⛷️",
  },
  {
    id: 120,
    question: "Quantas rodas tem um skate?",
    options: ["2", "4", "6", "8"],
    correctAnswer: 1,
    hint: "Quatro.",
    emoji: "🛹",
  },
  {
    id: 121,
    question: "Qual é o esporte praticado em cavalo?",
    options: ["Equitação", "Hipismo", "Polo", "Todas as anteriores"],
    correctAnswer: 3,
    hint: "Todas envolvem cavalo.",
    emoji: "🐴",
  },
  {
    id: 122,
    question: "Quantos rounds tem um jogo de boxe?",
    options: ["2", "3", "12", "15"],
    correctAnswer: 2,
    hint: "Geralmente 12.",
    emoji: "🥊",
  },
  {
    id: 123,
    question: "Qual é o esporte praticado em tatami?",
    options: ["Judô", "Karatê", "Taekwondo", "Kung Fu"],
    correctAnswer: 0,
    hint: "É um esporte oriental.",
    emoji: "🥋",
  },
  {
    id: 124,
    question: "Quantos jogadores tem um time de hóquei?",
    options: ["4", "5", "6", "7"],
    correctAnswer: 2,
    hint: "Seis.",
    emoji: "🏒",
  },
  {
    id: 125,
    question: "Qual é o esporte praticado em pista?",
    options: ["Corrida", "Atletismo", "Ciclismo", "Todas as anteriores"],
    correctAnswer: 3,
    hint: "Todas são praticadas em pista.",
    emoji: "🏃",
  },
  {
    id: 126,
    question: "Quantos pontos vale um gol no futebol?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 0,
    hint: "Um.",
    emoji: "⚽",
  },
  {
    id: 127,
    question: "Qual é o esporte praticado em água?",
    options: ["Surfe", "Vela", "Remo", "Todas as anteriores"],
    correctAnswer: 3,
    hint: "Todas são praticadas em água.",
    emoji: "🌊",
  },
  {
    id: 128,
    question: "Quantos pontos vale um cesto no basquete?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    hint: "Geralmente 2.",
    emoji: "🏀",
  },
  {
    id: 129,
    question: "Qual é o esporte praticado em neve?",
    options: ["Esqui", "Snowboard", "Curling", "Todas as anteriores"],
    correctAnswer: 3,
    hint: "Todas são praticadas em neve.",
    emoji: "❄️",
  },
  {
    id: 130,
    question: "Quantos jogadores tem um time de beisebol?",
    options: ["7", "8", "9", "10"],
    correctAnswer: 2,
    hint: "Nove.",
    emoji: "⚾",
  },

  // Perguntas sobre Cultura (131-170)
  {
    id: 131,
    question: "Qual é o instrumento musical mais popular?",
    options: ["Violino", "Guitarra", "Piano", "Flauta"],
    correctAnswer: 1,
    hint: "Tem 6 cordas.",
    emoji: "🎸",
  },
  {
    id: 132,
    question: "Quantas cordas tem um violão?",
    options: ["4", "5", "6", "7"],
    correctAnswer: 2,
    hint: "Seis.",
    emoji: "🎸",
  },
  {
    id: 133,
    question: "Qual é o instrumento de sopro mais popular?",
    options: ["Trompete", "Saxofone", "Flauta", "Trombone"],
    correctAnswer: 2,
    hint: "É o mais simples.",
    emoji: "🪈",
  },
  {
    id: 134,
    question: "Qual é o instrumento de percussão mais popular?",
    options: ["Tambor", "Bateria", "Pandeiro", "Triângulo"],
    correctAnswer: 1,
    hint: "Tem vários tambores.",
    emoji: "🥁",
  },
  {
    id: 135,
    question: "Quantas teclas tem um piano?",
    options: ["60", "80", "88", "100"],
    correctAnswer: 2,
    hint: "Mais de 80.",
    emoji: "🎹",
  },
  {
    id: 136,
    question: "Qual é o gênero musical mais popular?",
    options: ["Rock", "Pop", "Clássica", "Hip-hop"],
    correctAnswer: 1,
    hint: "É moderno.",
    emoji: "🎵",
  },
  {
    id: 137,
    question: "Qual é o dança mais famosa do Brasil?",
    options: ["Forró", "Samba", "Frevo", "Xaxado"],
    correctAnswer: 1,
    hint: "É o carnaval.",
    emoji: "💃",
  },
  {
    id: 138,
    question: "Qual é o dança mais famosa da Espanha?",
    options: ["Tango", "Flamenco", "Salsa", "Bachata"],
    correctAnswer: 1,
    hint: "Tem castanholas.",
    emoji: "💃",
  },
  {
    id: 139,
    question: "Qual é o dança mais famosa da Argentina?",
    options: ["Samba", "Flamenco", "Tango", "Salsa"],
    correctAnswer: 2,
    hint: "É apaixonada.",
    emoji: "💃",
  },
  {
    id: 140,
    question: "Qual é o dança mais famosa de Cuba?",
    options: ["Samba", "Salsa", "Tango", "Flamenco"],
    correctAnswer: 1,
    hint: "É caribenha.",
    emoji: "💃",
  },
  {
    id: 141,
    question: "Qual é o filme mais famoso de todos os tempos?",
    options: ["Titanic", "Avatar", "Homem-Aranha", "Senhor dos Anéis"],
    correctAnswer: 0,
    hint: "Tem um navio.",
    emoji: "🎬",
  },
  {
    id: 142,
    question: "Qual é o ator mais famoso do mundo?",
    options: ["Tom Cruise", "Johnny Depp", "Brad Pitt", "Leonardo DiCaprio"],
    correctAnswer: 3,
    hint: "Esteve em Titanic.",
    emoji: "🎭",
  },
  {
    id: 143,
    question: "Qual é a atriz mais famosa do mundo?",
    options: ["Angelina Jolie", "Scarlett Johansson", "Julia Roberts", "Meryl Streep"],
    correctAnswer: 0,
    hint: "Tem Jolie no sobrenome.",
    emoji: "🎭",
  },
  {
    id: 144,
    question: "Qual é o diretor de cinema mais famoso?",
    options: ["Spielberg", "Scorsese", "Kubrick", "Hitchcock"],
    correctAnswer: 0,
    hint: "Tem Spielberg no nome.",
    emoji: "🎬",
  },
  {
    id: 145,
    question: "Qual é o livro mais vendido do mundo?",
    options: ["Harry Potter", "Bíblia", "Senhor dos Anéis", "Dom Casmurro"],
    correctAnswer: 1,
    hint: "É religioso.",
    emoji: "📖",
  },
  {
    id: 146,
    question: "Qual é o autor mais famoso de todos os tempos?",
    options: ["Shakespeare", "Cervantes", "Dante", "Homero"],
    correctAnswer: 0,
    hint: "Escreveu Hamlet.",
    emoji: "✍️",
  },
  {
    id: 147,
    question: "Qual é o pintor mais famoso de todos os tempos?",
    options: ["Picasso", "Van Gogh", "Leonardo da Vinci", "Michelangelo"],
    correctAnswer: 2,
    hint: "Pintou a Mona Lisa.",
    emoji: "🎨",
  },
  {
    id: 148,
    question: "Qual é o compositor mais famoso de todos os tempos?",
    options: ["Mozart", "Beethoven", "Bach", "Chopin"],
    correctAnswer: 1,
    hint: "Era surdo.",
    emoji: "🎼",
  },
  {
    id: 149,
    question: "Qual é o museu mais famoso do mundo?",
    options: ["Louvre", "British Museum", "Hermitage", "Prado"],
    correctAnswer: 0,
    hint: "Fica em Paris.",
    emoji: "🏛️",
  },
  {
    id: 150,
    question: "Qual é o monumento mais famoso do mundo?",
    options: ["Big Ben", "Torre Eiffel", "Cristo Redentor", "Estátua da Liberdade"],
    correctAnswer: 1,
    hint: "Fica em Paris.",
    emoji: "🗼",
  },

  // Perguntas sobre Tecnologia (151-190)
  {
    id: 151,
    question: "Quem inventou o computador?",
    options: ["Bill Gates", "Steve Jobs", "Alan Turing", "Charles Babbage"],
    correctAnswer: 3,
    hint: "Tem Babbage no nome.",
    emoji: "💻",
  },
  {
    id: 152,
    question: "Quem inventou a internet?",
    options: ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Vint Cerf"],
    correctAnswer: 2,
    hint: "Tem Berners-Lee no nome.",
    emoji: "🌐",
  },
  {
    id: 153,
    question: "Quem inventou o telefone?",
    options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"],
    correctAnswer: 1,
    hint: "Tem Bell no nome.",
    emoji: "☎️",
  },
  {
    id: 154,
    question: "Quem inventou a lâmpada?",
    options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Guglielmo Marconi"],
    correctAnswer: 1,
    hint: "Tem Edison no nome.",
    emoji: "💡",
  },
  {
    id: 155,
    question: "Quem inventou o rádio?",
    options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Guglielmo Marconi"],
    correctAnswer: 3,
    hint: "Tem Marconi no nome.",
    emoji: "📻",
  },
  {
    id: 156,
    question: "Qual é a empresa de tecnologia mais valiosa do mundo?",
    options: ["Microsoft", "Google", "Apple", "Amazon"],
    correctAnswer: 2,
    hint: "Tem maçã no logo.",
    emoji: "🍎",
  },
  {
    id: 157,
    question: "Qual é o sistema operacional mais usado?",
    options: ["Mac", "Linux", "Windows", "Android"],
    correctAnswer: 2,
    hint: "Tem Windows no nome.",
    emoji: "🪟",
  },
  {
    id: 158,
    question: "Qual é o navegador mais usado?",
    options: ["Firefox", "Safari", "Chrome", "Edge"],
    correctAnswer: 2,
    hint: "Tem Chrome no nome.",
    emoji: "🌐",
  },
  {
    id: 159,
    question: "Qual é a rede social mais popular?",
    options: ["Twitter", "Instagram", "Facebook", "TikTok"],
    correctAnswer: 2,
    hint: "Tem Face no nome.",
    emoji: "👤",
  },
  {
    id: 160,
    question: "Qual é o aplicativo de mensagens mais popular?",
    options: ["Telegram", "Signal", "WhatsApp", "Viber"],
    correctAnswer: 2,
    hint: "Tem WhatsApp no nome.",
    emoji: "💬",
  },
  {
    id: 161,
    question: "Quantos bits tem um byte?",
    options: ["4", "8", "16", "32"],
    correctAnswer: 1,
    hint: "Oito.",
    emoji: "💾",
  },
  {
    id: 162,
    question: "Quantos bytes tem um kilobyte?",
    options: ["100", "500", "1000", "2000"],
    correctAnswer: 2,
    hint: "Mil.",
    emoji: "💾",
  },
  {
    id: 163,
    question: "Quantos megabytes tem um gigabyte?",
    options: ["100", "500", "1000", "2000"],
    correctAnswer: 2,
    hint: "Mil.",
    emoji: "💾",
  },
  {
    id: 164,
    question: "Qual é o processador mais rápido?",
    options: ["Intel", "AMD", "Qualcomm", "ARM"],
    correctAnswer: 0,
    hint: "Tem Intel no nome.",
    emoji: "⚙️",
  },
  {
    id: 165,
    question: "Qual é a placa de vídeo mais popular?",
    options: ["AMD", "Nvidia", "Intel", "Qualcomm"],
    correctAnswer: 1,
    hint: "Tem Nvidia no nome.",
    emoji: "🎮",
  },
  {
    id: 166,
    question: "Qual é o console de videogame mais vendido?",
    options: ["Xbox", "PlayStation", "Nintendo", "Sega"],
    correctAnswer: 1,
    hint: "Tem PlayStation no nome.",
    emoji: "🎮",
  },
  {
    id: 167,
    question: "Qual é o videogame mais vendido de todos os tempos?",
    options: ["Super Mario Bros", "Tetris", "Wii Sports", "Grand Theft Auto"],
    correctAnswer: 2,
    hint: "Tem Wii no nome.",
    emoji: "🎮",
  },
  {
    id: 168,
    question: "Qual é a câmera mais popular para fotos?",
    options: ["Canon", "Nikon", "Sony", "Fujifilm"],
    correctAnswer: 0,
    hint: "Tem Canon no nome.",
    emoji: "📷",
  },
  {
    id: 169,
    question: "Qual é a marca de smartphone mais popular?",
    options: ["Samsung", "Apple", "Xiaomi", "Huawei"],
    correctAnswer: 1,
    hint: "Tem Apple no nome.",
    emoji: "📱",
  },
  {
    id: 170,
    question: "Qual é o sistema operacional para smartphones mais popular?",
    options: ["iOS", "Android", "Windows Phone", "Blackberry"],
    correctAnswer: 1,
    hint: "Tem Android no nome.",
    emoji: "📱",
  },

  // Perguntas sobre Natureza (171-210)
  {
    id: 171,
    question: "Qual é a árvore mais alta do mundo?",
    options: ["Sequoia", "Eucalipto", "Pinheiro", "Carvalho"],
    correctAnswer: 0,
    hint: "Tem Sequoia no nome.",
    emoji: "🌲",
  },
  {
    id: 172,
    question: "Qual é a flor mais bonita do mundo?",
    options: ["Rosa", "Lótus", "Orquídea", "Girassol"],
    correctAnswer: 2,
    hint: "Tem Orquídea no nome.",
    emoji: "🌸",
  },
  {
    id: 173,
    question: "Qual é o animal mais venenoso do mundo?",
    options: ["Cobra", "Escorpião", "Sapo venenoso", "Aranha"],
    correctAnswer: 2,
    hint: "É um sapo.",
    emoji: "🐸",
  },
  {
    id: 174,
    question: "Qual é o animal mais forte do mundo?",
    options: ["Elefante", "Leão", "Formiga", "Urso"],
    correctAnswer: 2,
    hint: "É uma formiga.",
    emoji: "🐜",
  },
  {
    id: 175,
    question: "Qual é o animal mais inteligente do mundo?",
    options: ["Cachorro", "Gato", "Golfinho", "Macaco"],
    correctAnswer: 2,
    hint: "É um golfinho.",
    emoji: "🐬",
  },
  {
    id: 176,
    question: "Qual é o pássaro mais rápido do mundo?",
    options: ["Águia", "Falcão", "Pombo", "Andorinha"],
    correctAnswer: 1,
    hint: "Tem Falcão no nome.",
    emoji: "🦅",
  },
  {
    id: 177,
    question: "Qual é o peixe mais grande do mundo?",
    options: ["Tubarão branco", "Tubarão baleia", "Atum", "Pirarucu"],
    correctAnswer: 1,
    hint: "Tem tubarão no nome.",
    emoji: "🐋",
  },
  {
    id: 178,
    question: "Qual é o inseto mais comum do mundo?",
    options: ["Formiga", "Barata", "Mosca", "Mosquito"],
    correctAnswer: 0,
    hint: "Tem Formiga no nome.",
    emoji: "🐜",
  },
  {
    id: 179,
    question: "Qual é a flor mais cheirosa do mundo?",
    options: ["Rosa", "Jasmim", "Lírio", "Narciso"],
    correctAnswer: 1,
    hint: "Tem Jasmim no nome.",
    emoji: "🌸",
  },
  {
    id: 180,
    question: "Qual é a árvore que produz chocolate?",
    options: ["Cacaueiro", "Coqueiro", "Mangueira", "Bananeira"],
    correctAnswer: 0,
    hint: "Tem Cacaueiro no nome.",
    emoji: "🌳",
  },
  {
    id: 181,
    question: "Qual é a fruta mais saudável?",
    options: ["Maçã", "Banana", "Laranja", "Morango"],
    correctAnswer: 0,
    hint: "Tem Maçã no nome.",
    emoji: "🍎",
  },
  {
    id: 182,
    question: "Qual é a verdura mais nutritiva?",
    options: ["Alface", "Espinafre", "Brócolis", "Cenoura"],
    correctAnswer: 1,
    hint: "Tem Espinafre no nome.",
    emoji: "🥬",
  },
  {
    id: 183,
    question: "Qual é o animal que dorme mais?",
    options: ["Gato", "Urso", "Coala", "Preguiça"],
    correctAnswer: 3,
    hint: "Tem Preguiça no nome.",
    emoji: "🦥",
  },
  {
    id: 184,
    question: "Qual é o animal que vive mais tempo?",
    options: ["Elefante", "Tartaruga", "Papagaio", "Baleia"],
    correctAnswer: 1,
    hint: "Tem Tartaruga no nome.",
    emoji: "🐢",
  },
  {
    id: 185,
    question: "Qual é o animal que pesa mais?",
    options: ["Elefante", "Hipopótamo", "Baleia azul", "Girafa"],
    correctAnswer: 2,
    hint: "Tem Baleia no nome.",
    emoji: "🐋",
  },
  {
    id: 186,
    question: "Qual é o animal que corre mais rápido?",
    options: ["Leão", "Gazela", "Guepardo", "Avestruz"],
    correctAnswer: 2,
    hint: "Tem Guepardo no nome.",
    emoji: "🐆",
  },
  {
    id: 187,
    question: "Qual é o animal que nada mais rápido?",
    options: ["Golfinho", "Tubarão", "Peixe-vela", "Atum"],
    correctAnswer: 2,
    hint: "Tem Peixe-vela no nome.",
    emoji: "🐠",
  },
  {
    id: 188,
    question: "Qual é o animal que voa mais alto?",
    options: ["Águia", "Condor", "Ganso selvagem", "Falcão"],
    correctAnswer: 2,
    hint: "Tem Ganso no nome.",
    emoji: "🦅",
  },
  {
    id: 189,
    question: "Qual é o animal que mergulha mais profundo?",
    options: ["Golfinho", "Baleia", "Pinguim", "Foca"],
    correctAnswer: 1,
    hint: "Tem Baleia no nome.",
    emoji: "🐋",
  },
  {
    id: 190,
    question: "Qual é o animal que salta mais alto?",
    options: ["Canguru", "Gafanhoto", "Pulga", "Sapo"],
    correctAnswer: 0,
    hint: "Tem Canguru no nome.",
    emoji: "🦘",
  },

  // Perguntas sobre Comida (191-230)
  {
    id: 191,
    question: "Qual é a comida mais popular do mundo?",
    options: ["Pizza", "Hambúrguer", "Arroz", "Macarrão"],
    correctAnswer: 2,
    hint: "É um grão.",
    emoji: "🍚",
  },
  {
    id: 192,
    question: "Qual é a bebida mais popular do mundo?",
    options: ["Café", "Chá", "Água", "Refrigerante"],
    correctAnswer: 2,
    hint: "É essencial para a vida.",
    emoji: "💧",
  },
  {
    id: 193,
    question: "Qual é a fruta mais vendida do mundo?",
    options: ["Maçã", "Banana", "Laranja", "Melancia"],
    correctAnswer: 1,
    hint: "Tem Banana no nome.",
    emoji: "🍌",
  },
  {
    id: 194,
    question: "Qual é a carne mais consumida do mundo?",
    options: ["Bovina", "Suína", "Frango", "Peixe"],
    correctAnswer: 2,
    hint: "Tem Frango no nome.",
    emoji: "🍗",
  },
  {
    id: 195,
    question: "Qual é o queijo mais famoso do mundo?",
    options: ["Cheddar", "Mozzarella", "Parmesão", "Suíço"],
    correctAnswer: 1,
    hint: "Tem Mozzarella no nome.",
    emoji: "🧀",
  },
  {
    id: 196,
    question: "Qual é o pão mais famoso do mundo?",
    options: ["Francês", "Integral", "Branco", "Sírio"],
    correctAnswer: 0,
    hint: "Tem Francês no nome.",
    emoji: "🥖",
  },
  {
    id: 197,
    question: "Qual é a sobremesa mais famosa do mundo?",
    options: ["Bolo", "Sorvete", "Chocolate", "Pudim"],
    correctAnswer: 1,
    hint: "Tem Sorvete no nome.",
    emoji: "🍦",
  },
  {
    id: 198,
    question: "Qual é a bebida alcoólica mais popular?",
    options: ["Vinho", "Cerveja", "Destilado", "Espumante"],
    correctAnswer: 1,
    hint: "Tem Cerveja no nome.",
    emoji: "🍺",
  },
  {
    id: 199,
    question: "Qual é o tempero mais usado?",
    options: ["Sal", "Pimenta", "Alho", "Cebola"],
    correctAnswer: 0,
    hint: "Tem Sal no nome.",
    emoji: "🧂",
  },
  {
    id: 200,
    question: "Qual é a erva aromática mais usada?",
    options: ["Orégano", "Manjericão", "Alecrim", "Salsa"],
    correctAnswer: 1,
    hint: "Tem Manjericão no nome.",
    emoji: "🌿",
  },
  {
    id: 201,
    question: "Qual é a fruta tropical mais popular?",
    options: ["Abacaxi", "Manga", "Coco", "Mamão"],
    correctAnswer: 0,
    hint: "Tem Abacaxi no nome.",
    emoji: "🍍",
  },
  {
    id: 202,
    question: "Qual é a verdura mais consumida?",
    options: ["Tomate", "Alface", "Cenoura", "Brócolis"],
    correctAnswer: 0,
    hint: "Tem Tomate no nome.",
    emoji: "🍅",
  },
  {
    id: 203,
    question: "Qual é o legume mais nutritivo?",
    options: ["Feijão", "Lentilha", "Grão-de-bico", "Ervilha"],
    correctAnswer: 0,
    hint: "Tem Feijão no nome.",
    emoji: "🫘",
  },
  {
    id: 204,
    question: "Qual é a castanha mais saudável?",
    options: ["Amendoim", "Castanha-do-pará", "Amêndoa", "Noz"],
    correctAnswer: 1,
    hint: "Tem Castanha no nome.",
    emoji: "🥜",
  },
  {
    id: 205,
    question: "Qual é o óleo mais saudável?",
    options: ["Óleo de soja", "Óleo de girassol", "Azeite", "Óleo de coco"],
    correctAnswer: 2,
    hint: "Tem Azeite no nome.",
    emoji: "🫒",
  },
  {
    id: 206,
    question: "Qual é o leite mais nutritivo?",
    options: ["Leite integral", "Leite desnatado", "Leite de cabra", "Leite de amêndoa"],
    correctAnswer: 0,
    hint: "Tem integral no nome.",
    emoji: "🥛",
  },
  {
    id: 207,
    question: "Qual é o iogurte mais saudável?",
    options: ["Iogurte natural", "Iogurte grego", "Iogurte com frutas", "Iogurte desnatado"],
    correctAnswer: 1,
    hint: "Tem grego no nome.",
    emoji: "🥛",
  },
  {
    id: 208,
    question: "Qual é o cereal mais nutritivo?",
    options: ["Aveia", "Trigo", "Milho", "Cevada"],
    correctAnswer: 0,
    hint: "Tem Aveia no nome.",
    emoji: "🌾",
  },
  {
    id: 209,
    question: "Qual é a semente mais saudável?",
    options: ["Linhaça", "Chia", "Gergelim", "Abóbora"],
    correctAnswer: 1,
    hint: "Tem Chia no nome.",
    emoji: "🌱",
  },
  {
    id: 210,
    question: "Qual é a especiaria mais cara do mundo?",
    options: ["Pimenta", "Cravo", "Açafrão", "Canela"],
    correctAnswer: 2,
    hint: "Tem Açafrão no nome.",
    emoji: "🧂",
  },

  // Perguntas sobre Saúde (211-250)
  {
    id: 211,
    question: "Quantas horas de sono um adulto precisa?",
    options: ["6", "7", "8", "9"],
    correctAnswer: 2,
    hint: "Oito horas.",
    emoji: "😴",
  },
  {
    id: 212,
    question: "Qual é a vitamina mais importante?",
    options: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina B"],
    correctAnswer: 2,
    hint: "Tem D no nome.",
    emoji: "💊",
  },
  {
    id: 213,
    question: "Qual é o mineral mais importante?",
    options: ["Ferro", "Cálcio", "Zinco", "Magnésio"],
    correctAnswer: 1,
    hint: "Tem Cálcio no nome.",
    emoji: "💊",
  },
  {
    id: 214,
    question: "Quantos litros de água deve beber por dia?",
    options: ["1", "2", "3", "4"],
    correctAnswer: 1,
    hint: "Dois litros.",
    emoji: "💧",
  },
  {
    id: 215,
    question: "Qual é o exercício mais saudável?",
    options: ["Corrida", "Natação", "Caminhada", "Ciclismo"],
    correctAnswer: 1,
    hint: "Tem Natação no nome.",
    emoji: "🏊",
  },
  {
    id: 216,
    question: "Quantas vezes por semana deve exercitar?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    hint: "Três vezes.",
    emoji: "🏃",
  },
  {
    id: 217,
    question: "Qual é a pressão arterial normal?",
    options: ["100/60", "120/80", "140/90", "160/100"],
    correctAnswer: 1,
    hint: "120/80.",
    emoji: "❤️",
  },
  {
    id: 218,
    question: "Qual é a frequência cardíaca normal?",
    options: ["40", "60", "100", "120"],
    correctAnswer: 1,
    hint: "Sessenta batidas.",
    emoji: "❤️",
  },
  {
    id: 219,
    question: "Qual é o IMC ideal?",
    options: ["15", "18", "22", "30"],
    correctAnswer: 2,
    hint: "Vinte e dois.",
    emoji: "⚖️",
  },
  {
    id: 220,
    question: "Qual é a idade ideal para começar a exercitar?",
    options: ["5", "10", "15", "20"],
    correctAnswer: 0,
    hint: "Cinco anos.",
    emoji: "👶",
  },
  {
    id: 221,
    question: "Qual é a idade ideal para parar de exercitar?",
    options: ["50", "60", "70", "Nunca"],
    correctAnswer: 3,
    hint: "Nunca é tarde.",
    emoji: "👴",
  },
  {
    id: 222,
    question: "Qual é o esporte mais seguro?",
    options: ["Futebol", "Basquete", "Natação", "Boxe"],
    correctAnswer: 2,
    hint: "Tem Natação no nome.",
    emoji: "🏊",
  },
  {
    id: 223,
    question: "Qual é a doença mais comum do mundo?",
    options: ["Gripe", "Resfriado", "Diabetes", "Hipertensão"],
    correctAnswer: 1,
    hint: "Tem Resfriado no nome.",
    emoji: "🤒",
  },
  {
    id: 224,
    question: "Qual é a doença mais mortal do mundo?",
    options: ["AIDS", "Câncer", "Doença cardíaca", "Malária"],
    correctAnswer: 2,
    hint: "Tem Doença cardíaca no nome.",
    emoji: "❤️",
  },
  {
    id: 225,
    question: "Qual é a vacina mais importante?",
    options: ["Gripe", "Poliomielite", "Sarampo", "Caxumba"],
    correctAnswer: 1,
    hint: "Tem Poliomielite no nome.",
    emoji: "💉",
  },
  {
    id: 226,
    question: "Qual é o remédio mais comum?",
    options: ["Aspirina", "Paracetamol", "Ibuprofeno", "Dipirona"],
    correctAnswer: 1,
    hint: "Tem Paracetamol no nome.",
    emoji: "💊",
  },
  {
    id: 227,
    question: "Qual é a parte do corpo mais forte?",
    options: ["Braço", "Perna", "Mandíbula", "Dedo"],
    correctAnswer: 2,
    hint: "Tem Mandíbula no nome.",
    emoji: "💪",
  },
  {
    id: 228,
    question: "Qual é a parte do corpo mais sensível?",
    options: ["Olho", "Ouvido", "Nariz", "Boca"],
    correctAnswer: 0,
    hint: "Tem Olho no nome.",
    emoji: "👁️",
  },
  {
    id: 229,
    question: "Qual é o sentido mais importante?",
    options: ["Olfato", "Paladar", "Visão", "Tato"],
    correctAnswer: 2,
    hint: "Tem Visão no nome.",
    emoji: "👁️",
  },
  {
    id: 230,
    question: "Qual é a idade média de vida?",
    options: ["60", "70", "80", "90"],
    correctAnswer: 1,
    hint: "Setenta anos.",
    emoji: "👴",
  },
  {
    id: 231,
    question: "Qual é o país com maior expectativa de vida?",
    options: ["Japão", "Suíça", "Singapura", "Islândia"],
    correctAnswer: 0,
    hint: "Tem Japão no nome.",
    emoji: "🇯🇵",
  },
  {
    id: 232,
    question: "Qual é o país com menor expectativa de vida?",
    options: ["Síria", "Afeganistão", "Serra Leoa", "Somália"],
    correctAnswer: 2,
    hint: "Tem Serra Leoa no nome.",
    emoji: "🌍",
  },
  {
    id: 233,
    question: "Qual é a causa mais comum de morte?",
    options: ["Acidente", "Doença", "Velhice", "Suicídio"],
    correctAnswer: 1,
    hint: "Tem Doença no nome.",
    emoji: "💀",
  },
  {
    id: 234,
    question: "Qual é o tipo de sangue mais raro?",
    options: ["O", "A", "B", "AB"],
    correctAnswer: 3,
    hint: "Tem AB no nome.",
    emoji: "🩸",
  },
  {
    id: 235,
    question: "Qual é o tipo de sangue mais comum?",
    options: ["O", "A", "B", "AB"],
    correctAnswer: 0,
    hint: "Tem O no nome.",
    emoji: "🩸",
  },
  {
    id: 236,
    question: "Quantas vezes o coração bate por minuto?",
    options: ["40", "60", "100", "120"],
    correctAnswer: 1,
    hint: "Sessenta vezes.",
    emoji: "❤️",
  },
  {
    id: 237,
    question: "Quantas vezes respiramos por minuto?",
    options: ["10", "15", "20", "30"],
    correctAnswer: 1,
    hint: "Quinze vezes.",
    emoji: "💨",
  },
  {
    id: 238,
    question: "Qual é a temperatura mais alta que o corpo aguenta?",
    options: ["40°C", "42°C", "44°C", "46°C"],
    correctAnswer: 1,
    hint: "42 graus.",
    emoji: "🌡️",
  },
  {
    id: 239,
    question: "Qual é a temperatura mais baixa que o corpo aguenta?",
    options: ["30°C", "28°C", "26°C", "24°C"],
    correctAnswer: 1,
    hint: "28 graus.",
    emoji: "🌡️",
  },
  {
    id: 240,
    question: "Qual é o osso mais longo do corpo?",
    options: ["Fêmur", "Tíbia", "Rádio", "Úmero"],
    correctAnswer: 0,
    hint: "Tem Fêmur no nome.",
    emoji: "🦴",
  },
  {
    id: 241,
    question: "Qual é o osso mais curto do corpo?",
    options: ["Estribo", "Martelo", "Bigorna", "Vômero"],
    correctAnswer: 0,
    hint: "Tem Estribo no nome.",
    emoji: "🦴",
  },
  {
    id: 242,
    question: "Quantos músculos tem o corpo humano?",
    options: ["300", "400", "500", "600"],
    correctAnswer: 2,
    hint: "Mais de 400.",
    emoji: "💪",
  },
  {
    id: 243,
    question: "Quantos nervos tem o corpo humano?",
    options: ["Milhões", "Bilhões", "Trilhões", "Quatrilhões"],
    correctAnswer: 1,
    hint: "Bilhões.",
    emoji: "🧠",
  },
  {
    id: 244,
    question: "Qual é a célula mais importante do corpo?",
    options: ["Neurônio", "Glóbulo branco", "Glóbulo vermelho", "Célula de pele"],
    correctAnswer: 0,
    hint: "Tem Neurônio no nome.",
    emoji: "🧬",
  },
  {
    id: 245,
    question: "Quantas células tem o corpo humano?",
    options: ["Milhões", "Bilhões", "Trilhões", "Quatrilhões"],
    correctAnswer: 2,
    hint: "Trilhões.",
    emoji: "🧬",
  },
  {
    id: 246,
    question: "Qual é o órgão mais pesado do corpo?",
    options: ["Coração", "Pulmão", "Fígado", "Cérebro"],
    correctAnswer: 2,
    hint: "Tem Fígado no nome.",
    emoji: "🫀",
  },
  {
    id: 247,
    question: "Qual é o órgão mais importante do corpo?",
    options: ["Coração", "Pulmão", "Cérebro", "Fígado"],
    correctAnswer: 2,
    hint: "Tem Cérebro no nome.",
    emoji: "🧠",
  },
  {
    id: 248,
    question: "Qual é a glândula mais importante do corpo?",
    options: ["Glândula salivar", "Glândula sudorípara", "Glândula pituitária", "Glândula tireóide"],
    correctAnswer: 2,
    hint: "Tem Glândula pituitária no nome.",
    emoji: "🧬",
  },
  {
    id: 249,
    question: "Qual é a hormônio mais importante do corpo?",
    options: ["Insulina", "Adrenalina", "Cortisol", "Testosterona"],
    correctAnswer: 0,
    hint: "Tem Insulina no nome.",
    emoji: "💊",
  },
  {
    id: 250,
    question: "Qual é o neurotransmissor mais importante do corpo?",
    options: ["Dopamina", "Serotonina", "Acetilcolina", "GABA"],
    correctAnswer: 1,
    hint: "Tem Serotonina no nome.",
    emoji: "🧠",
  },
];
